unpackaged/objects/Capstone_Module__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Capstone Project Proposal</relationshipLabel>
        <relationshipName>Capstone_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Description__c</fullName>
        <label>Project Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Title__c</fullName>
        <label>Project Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervision__c</fullName>
        <label>Supervision</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Capstone Module</label>
    <nameField>
        <displayFormat>CM-{0000000000}</displayFormat>
        <label>Capstone Module ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capstone Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Supervisor</fullName>
                </value>
                <value>
                    <fullName>Supervisor Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Head of Study</fullName>
                </value>
                <value>
                    <fullName>Head of Study Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Ethics Committee</fullName>
                </value>
                <value>
                    <fullName>Ethics Committee Approved</fullName>
                </value>
                <value>
                    <fullName>Ethics Committee Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending VR</fullName>
                </value>
                <value>
                    <fullName>VR Approved</fullName>
                </value>
                <value>
                    <fullName>VR Rejected</fullName>
                </value>
                <value>
                    <fullName>Head of Study Approved</fullName>
                    <isActive>false</isActive>
                    <label>Head of Study Approved</label>
                </value>
                <value>
                    <fullName>Supervisor Approved</fullName>
                    <isActive>false</isActive>
                    <label>Supervisor Approved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Capstone_Approval_Status__c</fullName>
        <label>(Not in Use) Capstone Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First Level Approval</fullName>
                </value>
                <value>
                    <fullName>Second Level Approval</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_1_Approver_Comments__c</fullName>
        <label>(Not Used) Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Level_1_Approver_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Level_1_Approver_Status__c</fullName>
        <description>(Capstone Module) not in use</description>
        <label>(Not in Use) Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approve</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_1_Approver__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_2_Approver_Comments__c</fullName>
        <label>(Not Used) Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Level_2_Approver_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Level_2_Approver_Status__c</fullName>
        <description>(Not in Use) Capstone Module</description>
        <label>(Not in Use) Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approve</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_2_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>equals</operation>
                <value>Supervisor</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Name)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Datetime_1st_Level_Approved__c</fullName>
        <label>Max Datetime 1st Level Approved</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Max_Datetime_2nd_Level_Approved__c</fullName>
        <label>Max Datetime 2nd Level Approved</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Max_Datetime_3rd_Level_Approved__c</fullName>
        <label>Max Datetime 3rd Level Approved</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_MC__c</fullName>
        <label>Total MC for semester</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Student information</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/REC_Form_Submitted__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>REC Form Submitted</relationshipLabel>
        <relationshipName>REC_Form_Submitted</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>REC Form Submitted</relationshipLabel>
        <relationshipName>REC_Form_Submitted</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>REC_Form_Submitted</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>REC Form Submitted</label>
    <nameField>
        <displayFormat>RI-{0000000000}</displayFormat>
        <label>REC ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REC Form Submitted</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CaseHelper.cls
global class CaseHelper {
    public static void caseAfterUpdate(List<Case> newCases, Map<Id, Case> oldCases){
        Id capstoneRecordTypeId = [select Id from RecordType where Name = 'Capstone Module'].Id;
        Id recRecordTypeId = [select Id from RecordType where Name = 'REC Form Submission'].Id;

        Set<Id> caseIds = new Set<Id>();
        for(Case c : newCases){
            caseIds.add(c.Id);
        }

        List<Attachment> certificates = [select Id,Name,Body,ParentId from Attachment where Name like 'Certificate%' and ParentId in: caseIds order by CreatedDate desc LIMIT 1000];
        List<Attachment> rescue = [select Id,Name,Body,ParentId from Attachment where Name like 'RESCUE%' and ParentId in: caseIds order by CreatedDate desc LIMIT 1000];
        List<Attachment> chser = [select Id,Name,Body,ParentId from Attachment where Name like 'CHSER%' and ParentId in: caseIds order by CreatedDate desc LIMIT 1000];
        List<Attachment> pis = [select Id,Name,Body,ParentId from Attachment where Name like 'PIS%' and ParentId in: caseIds order by CreatedDate desc LIMIT 1000];
        List<Attachment> icf = [select Id,Name,Body,ParentId from Attachment where Name like 'ICF%' and ParentId in: caseIds order by CreatedDate desc LIMIT 1000];
        List<Attachment> fsp = [select Id,Name,Body,ParentId from Attachment where Name like 'FSP%' and ParentId in: caseIds order by CreatedDate desc LIMIT 1000];

        Map<String, Case> cases = new Map<String, Case>([
                select
                Id, (select Id from REC_Form_Submitted__r)
                from Case
                Where Id IN: caseIds
        ]);

        List<Attachment> attachments = new List<Attachment>();

        for(Case c : newCases){
            Case oldCase = oldCases.get(c.Id);

            if(c.RecordTypeId == capstoneRecordTypeId){
                if(c.Level_1_Approver_Status__c != oldCase.Level_1_Approver_Status__c && c.Level_1_Approver_Status__c == 'Approve'){
                    if(String.isNotEmpty(c.Level_2_Approver__c) && String.isNotEmpty(c.Level_2_Approver_Email__c)){
                        CaseHelper.sendCapstoneApprovalNotification(c, '2');
                    }
                }else if(c.Level_1_Approver_Status__c != oldCase.Level_1_Approver_Status__c && c.Level_1_Approver_Status__c == 'Reject'){
                    CaseHelper.sendCapstoneRejectedApprovalNotification(c, c.Level_1_Approver__c, c.Level_1_Approver_Email__c, c.Level_1_Approver_Comments__c, 'owner');
                    CaseHelper.sendCapstoneRejectedApprovalNotification(c, c.Level_1_Approver__c, c.Level_1_Approver_Email__c, c.Level_1_Approver_Comments__c, 'student');
                }
            }else if(c.RecordTypeId == recRecordTypeId){
                if(c.Approval_Status__c == 'Ethics Committee Approved'){
                    List<REC_Form_Submitted__c> recs = cases.get(c.Id).REC_Form_Submitted__r;

                    for(REC_Form_Submitted__c rec : recs){
                        List<Attachment> caseAttachments = new List<Attachment>();

                        Attachment certificateAttachment = getCaseAttachment(c.Id, certificates);
                        Attachment rescueAttachment = getCaseAttachment(c.Id, rescue);
                        Attachment chserAttachment = getCaseAttachment(c.Id, chser);
                        Attachment pisAttachment = getCaseAttachment(c.Id, pis);
                        Attachment icfAttachment = getCaseAttachment(c.Id, icf);
                        Attachment fspAttachment = getCaseAttachment(c.Id, fsp);

                        if(certificateAttachment != null){
                            caseAttachments.add(certificateAttachment);
                        }
                        if(rescueAttachment != null){
                            caseAttachments.add(rescueAttachment);
                        }
                        if(chserAttachment != null){
                            caseAttachments.add(chserAttachment);
                        }
                        if(pisAttachment != null){
                            caseAttachments.add(pisAttachment);
                        }
                        if(icfAttachment != null){
                            caseAttachments.add(icfAttachment);
                        }
                        if(fspAttachment != null){
                            caseAttachments.add(fspAttachment);
                        }

                        /*
                        if(certificates.size() > 0){
                            caseAttachments.add(certificates.get(0));
                        }

                        if(rescue.size() > 0){
                            caseAttachments.add(rescue.get(0));
                        }

                        if(chser.size() > 0){
                            caseAttachments.add(chser.get(0));
                        }

                        if(pis.size() > 0){
                            caseAttachments.add(pis.get(0));
                        }

                        if(icf.size() > 0){
                            caseAttachments.add(icf.get(0));
                        }

                        if(fsp.size() > 0){
                            caseAttachments.add(fsp.get(0));
                        }
                        */

                        for(Attachment attachment : caseAttachments){
                            attachments.add(new Attachment(ParentId = rec.Id, Body = attachment.Body, Name = attachment.Name));
                        }
                    }
                }
            }
        }

        if(attachments.size() > 0) insert attachments;
    }

    private static Attachment getCaseAttachment(Id caseID, List<Attachment> attachments){
        if(attachments.size() > 0){
            for(Attachment attachment : attachments){
                if(attachment.ParentId == caseID){
                    return attachment;
                }
            }
        }

        return null;
    }

    @future(callout=true)
    public static void updateStudentModuleTotalMC(String CaseID, Integer TotalMC){
        Case c = [select Id, Total_MC__c from Case where Id =: CaseID];
        c.Total_MC__c = Decimal.valueOf(TotalMC.format());
        
        update c;
    }
    
    @future(callout=true)
    public static void updateApprovalCase(String level, String caseID, String status1, String comment1, String status2, String comment2, String capstoneApproval){
        Case c = [select 
                    Id,Level_1_Approver_Status__c,Level_1_Approver_Comments__c,Level_2_Approver_Status__c,
                    Level_2_Approver_Comments__c,Capstone_Approval_Status__c,OwnerId 
                  from Case where Id =: caseId];
        
        if(level == '1'){
            c.Level_1_Approver_Status__c = status1;
            c.Level_1_Approver_Comments__c = comment1;    
        }else{
            c.Level_2_Approver_Status__c = status2;
            c.Level_2_Approver_Comments__c = comment2;
        }
        
        c.Capstone_Approval_Status__c = capstoneApproval;
        
        update c;
        
        if(c.Capstone_Approval_Status__c == 'Final Approval'){
            User user = [select Id from User where Id =: c.OwnerId];
            
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments('Submitted for approval. Please approve.');
            req.setObjectId(caseID);
            Approval.ProcessResult result = Approval.process(req);    
        }
    }
    
    public static void sendCapstoneApprovalNotification(Case c, String level){
        EmailTemplate emailTemplate = [select Id, Subject, HtmlValue, Body from EmailTemplate where Name = 'Capstone Email Approval Template'];
        
        String approver = '';
        if(level.equalsIgnoreCase('1')){
            approver = c.Level_1_Approver__c;
        }else{
            approver = [select Name from Contact where Id =: c.Level_2_Approver__c].Name;
        }

        Contact student = [select Name,Student_Identity__c,Email,Current_Year__c,Major__c from Contact where Id =: c.ContactId];
        Capstone_Module__c project = [select Id,Project_Title__c,Project_Description__c,Supervision__c from Capstone_Module__c where Case__c =: c.Id];
        
        String link = 'dev-yalenus-dev.cs31.force.com/CapstoneModuleApproval?level=' + level + '&Email=' + (level == '1' ? c.Level_1_Approver_Email__c : c.Level_2_Approver_Email__c)  + '&id=' + project.Id;
        
        String htmlBody = emailTemplate.HtmlValue;
        htmlBody = htmlBody.replace('{!approver}', approver);
        htmlBody = htmlBody.replace('{!studentId}', student.Student_Identity__c);
        htmlBody = htmlBody.replace('{!studentName}', student.Name);
        htmlBody = htmlBody.replace('{!studentEmail}', Student.Email);
        htmlBody = htmlBody.replace('{!studentCurrentYear}', student.Current_Year__c);
        htmlBody = htmlBody.replace('{!studentMajor}', student.Major__c);
        htmlBody = htmlBody.replace('{!projectTitle}', project.Project_Title__c);
        htmlBody = htmlBody.replace('{!projectDescription}', project.Project_Description__c);
        htmlBody = htmlBody.replace('{!projectSupervision}', (String.isNotEmpty(project.Supervision__c) ? project.Supervision__c : ''));
        htmlBody = htmlBody.replace('{!approvalLink}', link);
        
        String plainBody = emailTemplate.Body;
        plainBody = plainBody.replace('{!approver}', approver);
        plainBody = plainBody.replace('{!studentId}', student.Student_Identity__c);
        plainBody = plainBody.replace('{!studentName}', student.Name);
        plainBody = plainBody.replace('{!studentEmail}', Student.Email);
        plainBody = plainBody.replace('{!studentCurrentYear}', student.Current_Year__c);
        plainBody = plainBody.replace('{!studentMajor}', student.Major__c);
        plainBody = plainBody.replace('{!projectTitle}', project.Project_Title__c);
        plainBody = plainBody.replace('{!projectDescription}', project.Project_Description__c);
        plainBody = plainBody.replace('{!projectSupervision}', (String.isNotEmpty(project.Supervision__c) ? project.Supervision__c : ''));
        plainBody = plainBody.replace('{!approvalLink}', link);
        
        // OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'donotreply@yale-nus.edu.sg'];                
        
        Messaging.Singleemailmessage email = new Messaging.Singleemailmessage();
        
        // email.setOrgWideEmailAddressId(owea.get(0).Id);
        //email.setReplyTo(c.Level_1_Approver_Email__c);
        //email.setSenderDisplayName(c.Level_1_Approver_Email__c);
        email.toAddresses = new String[]{(level == '1' ? c.Level_1_Approver_Email__c : c.Level_2_Approver_Email__c)};
        //email.setTargetObjectId(c.Id);
        //email.setSaveAsActivity(true);
            
        email.setSubject(emailTemplate.Subject);
        email.setHtmlBody(htmlBody);
        email.setPlainTextBody(plainBody);
        
        Messaging.sendEmail(new Messaging.SingleEmailmessage[] {email});
    }
    
    public static void sendCapstoneRejectedApprovalNotification(Case c, String rejectedName, String rejectedEmail, String rejectedComments, String recipient){
        User u = [select Id,Name,Email from User where id =: c.OwnerId];
        Contact student = [select Id,Name,Email from Contact where Id =: c.ContactId];
        Capstone_Module__c project = [select Id,Project_Title__c,Project_Description__c,Supervision__c from Capstone_Module__c where Case__c =: c.Id];
        
        EmailTemplate emailTemplate = [select Id, Subject, HtmlValue, Body from EmailTemplate where Name = 'Capstone Rejected Approval Email Template'];
        
        String htmlBody = emailTemplate.HtmlValue;
        htmlBody = htmlBody.replace('{!name}', (recipient == 'owner' ? u.Name : student.Name));
        htmlBody = htmlBody.replace('{!caseNumber}', c.CaseNumber);
        htmlBody = htmlBody.replace('{!projectTitle}', project.Project_Title__c);
        htmlBody = htmlBody.replace('{!projectDescription}', project.Project_Description__c);
        htmlBody = htmlBody.replace('{!projectSupervision}', (String.isNotEmpty(project.Supervision__c) ? project.Supervision__c : ''));
        htmlBody = htmlBody.replace('{!rejectedName}', rejectedName);
        htmlBody = htmlBody.replace('{!rejectedEmail}', rejectedEmail);
        htmlBody = htmlBody.replace('{!rejectedComments}', rejectedComments);
        
        String plainBody = emailTemplate.Body;
        plainBody = plainBody.replace('{!name}', (recipient == 'owner' ? u.Name : student.Name));
        plainBody = plainBody.replace('{!caseNumber}', c.CaseNumber);
        plainBody = plainBody.replace('{!projectTitle}', project.Project_Title__c);
        plainBody = plainBody.replace('{!projectDescription}', project.Project_Description__c);
        plainBody = plainBody.replace('{!projectSupervision}', (String.isNotEmpty(project.Supervision__c) ? project.Supervision__c : ''));
        plainBody = plainBody.replace('{!rejectedName}', rejectedName);
        plainBody = plainBody.replace('{!rejectedEmail}', rejectedEmail);
        plainBody = plainBody.replace('{!rejectedComments}', rejectedComments);
        
        Messaging.Singleemailmessage email = new Messaging.Singleemailmessage();
        email.toAddresses = new String[]{(recipient == 'owner' ? u.Email : student.Email)};
        email.setSubject(emailTemplate.Subject);
        email.setHtmlBody(htmlBody);
        email.setPlainTextBody(plainBody);
        
        Messaging.sendEmail(new Messaging.SingleEmailmessage[] {email});
    }
    
    /*
    Define max datetime, to remember the approver to approve the case
    */
    public static void setTimeApprovalReminder(List<Case> listCases){
        BusinessHours BH = [select id from businesshours where IsDefault=true limit 1];
        Datetime threeDaysBHFromNow = BusinessHours.Add(BH.Id, System.now(), 108000000); //108000000 (MilliSecond) = 3 days from created date
        
        for(Case c : listCases){
            if(c.Approval_Status__c == 'Pending Supervisor'){
                c.Max_Datetime_1st_Level_Approved__c = threeDaysBHFromNow;
            }
            else if(c.Approval_Status__c == 'Pending Head of Study'){
                c.Max_Datetime_2nd_Level_Approved__c = threeDaysBHFromNow;
            }
            else if(c.Approval_Status__c == 'Pending Ethics Committee'){
                c.Max_Datetime_3rd_Level_Approved__c = threeDaysBHFromNow;
            }
            //System.debug('currentuserId ' + currentuserId);
        }
    }
}