unpackaged/objects/Capstone_Module__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Capstone Project Proposal</relationshipLabel>
        <relationshipName>Capstone_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Description__c</fullName>
        <label>Project Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Title__c</fullName>
        <label>Project Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervision__c</fullName>
        <label>Supervision</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Capstone Module</label>
    <nameField>
        <displayFormat>CM-{0000000000}</displayFormat>
        <label>Capstone Module ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capstone Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Capstone_Approval_Status__c</fullName>
        <label>(Not in Use) Capstone Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First Level Approval</fullName>
                </value>
                <value>
                    <fullName>Second Level Approval</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_1_Approver_Comments__c</fullName>
        <label>(Not Used) Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Level_1_Approver_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Level_1_Approver_Status__c</fullName>
        <description>(Capstone Module) not in use</description>
        <label>(Not in Use) Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approve</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_1_Approver__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_2_Approver_Comments__c</fullName>
        <label>(Not Used) Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Level_2_Approver_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Level_2_Approver_Status__c</fullName>
        <description>(Not in Use) Capstone Module</description>
        <label>(Not in Use) Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approve</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level_2_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Type__c</field>
                <operation>equals</operation>
                <value>Supervisor</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Name)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Student information</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CapstoneModuleApprovalController.cls
public class CapstoneModuleApprovalController extends ControllerBase{
    
    public Capstone_Module__c project {set; get;}
    public Contact approver {set; get;}
    public Contact student {set; get;}
    public Case c {set;get;}
    public Boolean firstApproval {set; get;}
    
    public Boolean approvalProcess {set; get;}
    
    private Map<String,String> params;
    private String caseID;
    
    
    public CapstoneModuleApprovalController(){
        params = this.getParameters();
        approvalProcess = true;
        
        try{
            project = [select Id,Case__c,Project_Title__c,Project_Description__c,Supervision__c from Capstone_Module__c where Id =: params.get('id')];
            
            if(params.get('level') == '1'){
                c = [select 
                        Id,ContactId,Level_1_Approver__c,Level_1_Approver_Email__c,Level_1_Approver_Status__c,
                        Level_1_Approver_Comments__c,Capstone_Approval_Status__c,OwnerId,CaseNumber 
                    from Case 
                    where Id =: project.Case__c];
                
                firstApproval = true;
            }else{
                c = [
                    select 
                        Id,ContactId,Level_2_Approver__c,Level_2_Approver_Email__c,Level_2_Approver_Status__c,Level_2_Approver_Comments__c,
                        Level_1_Approver__c,Level_1_Approver_Status__c,Level_1_Approver_Comments__c,Capstone_Approval_Status__c,OwnerId,CaseNumber
                    from Case 
                    where Id =: project.Case__c
                ];
                
                approver = [select Name from Contact where Id =: c.Level_2_Approver__c ];
                firstApproval = false;
            }
            
            student = [select Name,Student_Identity__c,Email,Current_Year__c,Major__c from Contact where Id =: c.ContactId];
            
            caseID = c.Id;
            c.Id = null;
        }catch(Exception e){
            this.showErrorMessage(e.getMessage());
        }
    }
    
    private Boolean secondLevelApproval(){
        Case cs = [select Id,Level_2_Approver_Email__c from Case where Id =: project.Case__c];
        
        if(String.isNotEmpty(cs.Level_2_Approver_Email__c)){
            return true;
        }
        
        return false;
    }
    
    public PageReference checkApproval(){
        if(params.get('level') == '1'){
            if(c.Level_1_Approver_Status__c == 'Reject' || c.Level_1_Approver_Status__c == 'Approve'){
                this.showErrorMessage('You already ' + c.Level_1_Approver_Status__c + ' this Capstone Project Proposal'); 
                approvalProcess = false;
            }
        }else{
            if(c.Level_2_Approver_Status__c == 'Reject' || c.Level_2_Approver_Status__c == 'Approve'){
                this.showErrorMessage('You already ' + c.Level_1_Approver_Status__c + ' this Capstone Project Proposal');
                approvalProcess = false;
            }
        }
        
        return null;
    }
    
    public PageReference process(){
        // update c;
        
        if(params.get('level') == '1'){
            if(secondLevelApproval()){
                this.showConfirmMessage('Thank you for the confirmation, this submission is being routed to the next approver.');
                if(c.Level_1_Approver_Status__c == 'Approve'){
                    c.Capstone_Approval_Status__c = 'Second Level Approval';    
                }
            }else{
                this.showConfirmMessage('Thank you for the confirmation.');
                if(c.Level_1_Approver_Status__c == 'Approve'){
                    c.Capstone_Approval_Status__c = 'Final Approval';    
                }
            }
        }else{
            this.showConfirmMessage('Thank you for the confirmation.');
            
            if(c.Level_2_Approver_Status__c == 'Approve'){
                c.Capstone_Approval_Status__c = 'Final Approval';
            }else{
                CaseHelper.sendCapstoneRejectedApprovalNotification(c, approver.Name, c.Level_2_Approver_Email__c, c.Level_2_Approver_Comments__c, 'owner');
                CaseHelper.sendCapstoneRejectedApprovalNotification(c, approver.Name, c.Level_2_Approver_Email__c, c.Level_2_Approver_Comments__c, 'student');
            }
        }
        
        // update c;
        approvalProcess = false;
        
        CaseHelper.updateApprovalCase(params.get('level'), caseID, c.Level_1_Approver_Status__c, c.Level_1_Approver_Comments__c, c.Level_2_Approver_Status__c, c.Level_2_Approver_Comments__c, c.Capstone_Approval_Status__c);
        
        //if(c.Capstone_Approval_Status__c == 'Final Approval'){
        //    System.debug('owner Id : ' + c.OwnerId);
        //  User user = [select Id from User where Id =: c.OwnerId];
        //    
        //    Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        //    req.setComments('Submitted for approval. Please approve.');
        //    req.setObjectId(caseID);
        //    Approval.ProcessResult result = Approval.process(req);    
        //}
        
        return null;
    }
}