unpackaged/objects/Capstone_Module__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Capstone Module Proposal Form</relationshipLabel>
        <relationshipName>Capstone_Modules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Capstone Module Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Supervisor_Exterent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Supervisor is not from Yale-NUS</label>
        <type>Checkbox</type>
    </fields>
    <label>Capstone Module</label>
    <nameField>
        <displayFormat>CM-{0000000000}</displayFormat>
        <label>Capstone Module ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capstone Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Capstone_Module_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Capstone_Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Capstone Module</label>
        <referenceTo>Capstone_Module__c</referenceTo>
        <relationshipLabel>Capstone Module Activities</relationshipLabel>
        <relationshipName>Capstone_Module_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Capstone Module Activity</label>
    <nameField>
        <displayFormat>CMA-{0000000000}</displayFormat>
        <label>Capstone Module Activity ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capstone Module Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Capstone_Module_Activity_Template__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <label>Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Capstone Module Activity Template</label>
    <nameField>
        <displayFormat>CMAT-{0000000000}</displayFormat>
        <label>Capstone Module Activity Template ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capstone Module Activity Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_of_Course__c</fullName>
        <label>Length of Course</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matric_Year__c</fullName>
        <label>Matric Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minor__c</fullName>
        <label>Current Minor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NRIC__c</fullName>
        <label>NRIC/FIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NUSNET_ID__c</fullName>
        <externalId>true</externalId>
        <label>NUSNET ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Residential_College__c</fullName>
        <label>Residential College</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active SEP</fullName>
                </value>
                <value>
                    <fullName>Active LOA</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Faculty</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Head of Study</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Residential_College__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Residential College History</relationshipLabel>
        <relationshipName>Residential_Colleges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_From__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_To__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Suite_No__c</fullName>
        <label>Suite No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Residential College</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Residential College ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residential Colleges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CapstoneModuleController.cls
public class CapstoneModuleController extends ControllerBase{

    public Contact contact {set; get;}
    public Case c {set; get;}
    public Capstone_Module__c capstoneModule {set; get;}
    public List<Capstone_Module_Activity__c> capstoneModuleActivities {set; get;}
    public List<Residential_College__c> rc {set; get;}
    public String residentialCollegeName {set; get;}
    // public String today {set; get;}
    public boolean showPartner {set; get;}
    public boolean showAffliation {set; get;}
    public String currentMajor {set; get;}
    public String firstApprover {set; get;}
    public String firstApprover2 {set; get;}
    public String secondApprover {set; get;}
    public String firstApproverEmail {set; get;}
    public String firstApproverEmail2 {set; get;}
    public String secondApproverEmail {set; get;}
    public List<SelectOption> firstApproverEmails {set; get;}
    public List<SelectOption> secondApproverEmails {set; get;}
    
    private Map<String, String> params;
    private List<Contact> approvers;
    
    public CapstoneModuleController(){
        params = this.getParameters();
        
        contact = [select Id,Name,Student_Identity__c,Email,Matric_Year__c,NRIC__c,Current_Year__c,Length_of_Course__c,Major__c,Minor__c,NUSNET_ID__c from Contact where NUSNET_ID__c =: params.get('nid')];
        rc = [select Id,Name,Date_To__c,Date_From__c,Suite_No__c from Residential_College__c where Contact__c =: contact.Id and Date_To__c = null limit 1];
        
        if(rc.size() > 0){
            residentialCollegeName = rc.get(0).Name;
        }else{
            residentialCollegeName = '-';
        }

        currentMajor = contact.Major__c;
        
        firstApproverEmail = null;
        secondApproverEmail = null;
        
        firstApproverEmails = new List<SelectOption>();
        secondApproverEmails = new List<SelectOption>();
        
        firstApproverEmails.add(new SelectOption('', '--None--'));
        secondApproverEmails.add(new SelectOption('', '--None--'));
        
        approvers = [select Id,Name,Email from Contact where Type__c = 'Supervisor' and Status__c = 'Active'];
        for(Contact approver:approvers){
            firstApproverEmails.add(new SelectOption(approver.Id, approver.Name));
            secondApproverEmails.add(new SelectOption(approver.Id, approver.Name));
        }
        
        if(params.get('status') == 'new'){
            // today = Datetime.now().format('dd MMMM yyyy');
            showAffliation = false;
            
            capstoneModule = new Capstone_Module__c();
            capstoneModule.Project_Supervisor_Exterent__c = false;
            capstoneModule.Date__c = System.today();
            capstoneModule.Contact__c = contact.Id;
            
            capstoneModuleActivities = new List<Capstone_Module_Activity__c>();
            List<Capstone_Module_Activity_Template__c> templates = [select Activity__c, Action__c from Capstone_Module_Activity_Template__c];
            
            for(Capstone_Module_Activity_Template__c cmat : templates){
                Capstone_Module_Activity__c cma = new Capstone_Module_Activity__c();
                cma.Activity__c = cmat.Activity__c;
                cma.Action__c = cmat.Action__c;
                
                capstoneModuleActivities.add(cma);
            }
            
            c = new Case();
            c.ContactId = contact.Id;
            c.Department__c = params.get('department');
            c.Type_Of_Enquiry__c = params.get('toe');
            c.RecordTypeId = [select Id from RecordType where Name = 'Capstone Module'].Id;
            if(params.get('subdepartment') != 'null'){
                c.Sub_Department__c = params.get('subdepartment');    
            }            
        }else{
            capstoneModule = [select Id,Name,Case__c,Contact__c,Project_Supervisor_Name__c,Project_Supervisor_Email__c,Project_Supervisor_Exterent__c,Project_Supervisor_Affliation__c,Co_Supervisor_Name__c,Co_Supervisor_Email__c,Project_Title__c,Project_Description__c,Supervision__c from Capstone_Module__c where Id =: params.get('cid')];
            capstoneModuleActivities = [select Id,Name,Capstone_Module__c,Activity__c,Action__c,Check__c from Capstone_Module_Activity__c where Capstone_Module__c =: capstoneModule.Id];
            c = [select Id,ContactId,Department__c,Type_Of_Enquiry__c,RecordTypeId,Sub_Department__c,Subject,Status,Origin,Priority,Start_Date__c,End_Date__c from Case where Id =: capstoneModule.Case__c];
            
            Datetime dt = datetime.newInstance(capstoneModule.Date__c.Year(), capstoneModule.Date__c.Month(), capstoneModule.Date__c.Day());
            // today = dt.format('dd MMMM yyyy');
        }
    }
    
    public void firstApproverOnChange(){
        if(String.isNotEmpty(firstApprover) && firstApprover != ''){
            for(Contact approver : approvers){
                if(approver.Id == firstApprover){
            		firstApproverEmail = approver.Email;        
                }
            }
        }else{
            firstApproverEmail = null;
        }
    }

    public void secondApproverOnChange(){
        if(String.isNotEmpty(secondApprover) && secondApprover != ''){
            for(Contact approver : approvers){
                if(approver.Id == secondApprover){
            		secondApproverEmail = approver.Email;        
                }
            }
        }else{
            secondApproverEmail = null;
        }
    }
    
    public void affliationOnChange(){
        if(capstoneModule.Project_Supervisor_Exterent__c){
            showAffliation = true;  
        }else{
            showAffliation = false;
        }
    }
    
    public PageReference cancel(){
        return new PageReference('/CaseView?nid=' + params.get('nid'));
    }
    
    public PageReference save(){
        if(params.get('status') == 'new'){
            if(capstoneModule.Project_Supervisor_Exterent__c){
                if(String.isEmpty(secondApprover)){
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Co Supervisor cannot be null if the project supervisor is not from YALE!'));
                    return null;
                }
            }

            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule = true;

            c.Subject = params.get('toe');
            c.Status = 'Open';
            c.Origin = 'Web';
            c.Priority = 'High';
            c.setOptions(dmo);
            
            if(capstoneModule.Project_Supervisor_Exterent__c){
                c.Level_1_Approver__c = firstApprover2;
                c.Level_1_Approver_Email__c = firstApproverEmail2;
                c.Level_2_Approver__c = secondApprover;
                c.Level_2_Approver_Email__c = secondApproverEmail;

                capstoneModule.Project_Supervisor_Name__c = firstApprover2;
                capstoneModule.Project_Supervisor_Email__c = firstApproverEmail2;

                if(String.isNotEmpty(secondApprover)){
                    capstoneModule.Co_Supervisor_Name__c = [select Name from Contact where Id =: secondApprover].Name;
                    capstoneModule.Co_Supervisor_Email__c = c.Level_2_Approver_Email__c;
                }
            }else{
                System.debug('approver : ' + firstApprover);
                System.debug('approver email : ' + firstApproverEmail);

                c.Level_1_Approver__c = [select Name from Contact where Id =: firstApprover].Name;
                c.Level_1_Approver_Email__c = firstApproverEmail;

                capstoneModule.Project_Supervisor_Name__c = c.Level_1_Approver__c;
                capstoneModule.Project_Supervisor_Email__c = firstApproverEmail;
            }

            
            c.Capstone_Approval_Status__c = 'First Level Approval';
            c.Capstone_Project_Title__c = capstoneModule.Project_Title__c;
            c.Capstone_Project_Description__c = capstoneModule.Project_Description__c;
            c.Capstone_Project_Supervision__c = capstoneModule.Supervision__c;
            insert c;
            
            capstoneModule.Case__c = c.Id;
            insert capstoneModule;
            
            /*
            for(Capstone_Module_Activity__c cma : capstoneModuleActivities){
                cma.Capstone_Module__c = capstoneModule.Id;
            }
            
            insert capstoneModuleActivities;
            */
        }else{
            update capstoneModule;
            //update capstoneModuleActivities;
        }
        
        return new PageReference('/CaseView?nid=' + params.get('nid'));
    }
}