unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Faculty_Advisor__c</fullName>
        <label>Faculty Advisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub  Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student Affairs</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Change Of Major</fullName>
                </value>
                <value>
                    <fullName>New Semester</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Experiential Opportunities</fullName>
                </value>
                <value>
                    <fullName>Fellowships and Graduate School</fullName>
                </value>
                <value>
                    <fullName>Leadership Development</fullName>
                </value>
                <value>
                    <fullName>RC Executives</fullName>
                </value>
                <value>
                    <fullName>Reg</fullName>
                </value>
                <value>
                    <fullName>VR</fullName>
                </value>
                <value>
                    <fullName>REC</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                    <isActive>false</isActive>
                    <label>Registry</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_Of_Enquiry__c</fullName>
        <label>Type of Enquiry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request for Transcripts</fullName>
                </value>
                <value>
                    <fullName>NS Deferment Letter</fullName>
                </value>
                <value>
                    <fullName>Request for Vice Rector Note</fullName>
                </value>
                <value>
                    <fullName>Summer Language Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Five Year Programme with Lee Kuan Yew School of Public Policy</fullName>
                </value>
                <value>
                    <fullName>Independent Reading and Research (IRR) Module Registration Form</fullName>
                </value>
                <value>
                    <fullName>Capstone Module Proposal Form</fullName>
                </value>
                <value>
                    <fullName>Request for Student Status Letter (Additional remarks needed)</fullName>
                </value>
                <value>
                    <fullName>Modules Add/Drop</fullName>
                </value>
                <value>
                    <fullName>2MC IRR/ 5MC Special Project</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Request for Change of Major/Minor</fullName>
                </value>
                <value>
                    <fullName>Request for Letter of Residence</fullName>
                </value>
                <value>
                    <fullName>Summer Independent Research</fullName>
                </value>
                <value>
                    <fullName>Summer Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Social Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Research</fullName>
                </value>
                <value>
                    <fullName>REC Form Submission</fullName>
                </value>
                <value>
                    <fullName>Leadership Ethics Application</fullName>
                </value>
                <value>
                    <fullName>NGO Bootcamp Application</fullName>
                </value>
                <value>
                    <fullName>Leadership Certificate Sign-up</fullName>
                </value>
                <value>
                    <fullName>Leadership Fundamentals Application</fullName>
                </value>
                <value>
                    <fullName>Intergroup Dialogue Interest</fullName>
                </value>
                <value>
                    <fullName>Request for Overloading/Underloading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Faculty</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Head of Study</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Student information</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Plan_Of_Study__c.object
<CustomObject>
    <fields>
        <fullName>Capstone_Advisor__c</fullName>
        <label>Capstone Advisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Plan Of Studies</relationshipLabel>
        <relationshipName>Plan_Of_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Faculty_Advisor__c</fullName>
        <label>Faculty Advisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Head_of_Studies__c</fullName>
        <label>Head of Studies for Major</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Of_Study__c</fullName>
        <label>Year of Study as of form submission</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year_Of_Study</valueSetName>
        </valueSet>
    </fields>
    <label>Plan Of Study</label>
    <nameField>
        <displayFormat>POS-{0000000000}</displayFormat>
        <label>Plan Of Study ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Of Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Progress_Report__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Advising__c</fullName>
        <label>Academic Advising</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Capstone_Advisor__c</fullName>
        <label>Capstone Advisor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Faculty_Advisor__c</fullName>
        <label>Faculty Advisor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Head_of_Study__c</fullName>
        <label>Head of Studies for Major</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Academic Progress Reports</relationshipLabel>
        <relationshipName>Progress_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_of_Study__c</fullName>
        <label>Year of Study</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>APR-{0000000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Vice_Rector_Note__c.object
<CustomObject>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <label>Date Issued</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Vice_Rector_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Please state reason for VRN request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Death in the family</fullName>
                </value>
                <value>
                    <fullName>Religious Holidays</fullName>
                </value>
                <value>
                    <fullName>Medical - Physical / Mental Health</fullName>
                </value>
                <value>
                    <fullName>Comparable Emergency</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vice Rector Note</label>
    <nameField>
        <displayFormat>VRN-{0000000000}</displayFormat>
        <label>Vice Rector Note ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vice Rector Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CaseViewController.cls
// For testing
// https://c.cs31.visual.force.com/apex/CaseView?sid=SID201609170000001

public class CaseViewController extends CommunityControllerBase{
    
    public List<Case> cases {set; get;}
    public Contact contact {set; get;}
    public List<Progress_Report__c> progressReports {set; get;}
    public List<Vice_Rector_Note__c> vrNotes {set; get;}
    public List<Plan_Of_Study__c> pos {set; get;}
    
    public Boolean showVRNote {set; get;}
    public Boolean showProgressReport {set; get;}
    
    private Map<String, String> params;
    
    public CaseViewController(){
        params = this.getParameters();
        
        contact = [select Id,Name,Student_Identity__c from Contact where Id =: ContactID];
        cases = [select Id,Department__c,Sub_Department__c,CaseNumber,Status,Type_of_Enquiry__c,Description,ContactId,CreatedDate from Case where ContactId =: contact.Id and Status = 'Open' order by LastModifiedDate desc];
        vrNotes = [select Id,Type__c,Date_Issued__c,Name from Vice_Rector_Note__c where Student__c =: contact.Id];
        pos = [select Id,Name,Year_Of_Study__c,Head_of_Studies__c,Capstone_Advisor__c,Faculty_Advisor__c from Plan_Of_Study__c where Contact__c =: contact.Id];
        this.loadProgressReports();
    }
    
    private void loadProgressReports(){
        progressReports = [select Id,Name,Academic_Advising__c,Capstone_Advisor__c,Head_of_Study__c,Year_of_Study__c,Faculty_Advisor__c from Progress_Report__c where Student__c =: contact.Id  and isDeleted = false order by date__c desc];
        
    }
    
    public PageReference caseDetail(){
        PageReference pr = Page.CaseDetail;
        pr.setRedirect(true);
        pr.getParameters().put('cid',this.getParameters().get('cid'));
        return pr;
    }
    
    public PageReference closeCase(){
        Case c = [select Id,isClosed from Case where Id =: getParameters().get('cid')];
        c.Status = 'Closed';
        c.Reason = 'Closed By Student';
        update c;
        
        return new PageReference('/apex/CaseView?sid=' + params.get('sid'));
    }
    
    public PageReference prEdit(){
        String pid = this.getParameters().get('pid');
        return new PageReference('/apex/ProgressReport?sid='+params.get('sid')+'&status=edit&pid='+pid);
    }
    
    public PageReference prDelete(){
        String pid = this.getParameters().get('pid');
        Progress_Report__c pr = [select Id,Name from Progress_Report__c where Id =: pid];
        delete pr;
        
        PageReference page = new PageReference('/apex/CaseView?sid=' + params.get('sid'));
        page.setRedirect(true);
        return page;
    }
    
    public PageReference vrNoteUpdate(){
        String vid = this.getParameters().get('vid');
        return new PageReference('/apex/VRNote?sid='+params.get('sid')+'&status=edit&vid='+vid);
    }
    
    public PageReference vrNoteDelete(){
        String vid = this.getParameters().get('vid');
        Vice_Rector_Note__c vr = [select Id,Name from Vice_Rector_Note__c where Id =: vid];
        delete vr;
        
        PageReference page = new PageReference('/apex/CaseView?sid=' + params.get('sid'));
        page.setRedirect(true);
        return page;
    }
}