unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Supervisor</fullName>
                </value>
                <value>
                    <fullName>Supervisor Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Head of Study</fullName>
                </value>
                <value>
                    <fullName>Head of Study Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending Ethics Committee</fullName>
                </value>
                <value>
                    <fullName>Ethics Committee Approved</fullName>
                </value>
                <value>
                    <fullName>Ethics Committee Rejected</fullName>
                </value>
                <value>
                    <fullName>Pending VR</fullName>
                </value>
                <value>
                    <fullName>VR Approved</fullName>
                </value>
                <value>
                    <fullName>VR Rejected</fullName>
                </value>
                <value>
                    <fullName>Head of Study Approved</fullName>
                    <isActive>false</isActive>
                    <label>Head of Study Approved</label>
                </value>
                <value>
                    <fullName>Supervisor Approved</fullName>
                    <isActive>false</isActive>
                    <label>Supervisor Approved</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub  Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student Affairs</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Change Of Major</fullName>
                </value>
                <value>
                    <fullName>New Semester</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Experiential Opportunities</fullName>
                </value>
                <value>
                    <fullName>Fellowships and Graduate School</fullName>
                </value>
                <value>
                    <fullName>Leadership Development</fullName>
                </value>
                <value>
                    <fullName>RC Executives</fullName>
                </value>
                <value>
                    <fullName>Reg</fullName>
                </value>
                <value>
                    <fullName>VR</fullName>
                </value>
                <value>
                    <fullName>REC</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                    <isActive>false</isActive>
                    <label>Registry</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_Of_Enquiry__c</fullName>
        <label>Type of Enquiry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request for Transcripts</fullName>
                </value>
                <value>
                    <fullName>NS Deferment Letter</fullName>
                </value>
                <value>
                    <fullName>Request for Vice Rector Note</fullName>
                </value>
                <value>
                    <fullName>Summer Language Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Five Year Programme with Lee Kuan Yew School of Public Policy</fullName>
                </value>
                <value>
                    <fullName>Independent Reading and Research (IRR) Module Registration Form</fullName>
                </value>
                <value>
                    <fullName>Capstone Module Proposal Form</fullName>
                </value>
                <value>
                    <fullName>Request for Student Status Letter (Additional remarks needed)</fullName>
                </value>
                <value>
                    <fullName>Modules Add/Drop</fullName>
                </value>
                <value>
                    <fullName>2MC IRR/ 5MC Special Project</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Request for Change of Major/Minor</fullName>
                </value>
                <value>
                    <fullName>Request for Letter of Residence</fullName>
                </value>
                <value>
                    <fullName>Summer Independent Research</fullName>
                </value>
                <value>
                    <fullName>Summer Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Social Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Research</fullName>
                </value>
                <value>
                    <fullName>REC Form Submission</fullName>
                </value>
                <value>
                    <fullName>Leadership Ethics Application</fullName>
                </value>
                <value>
                    <fullName>NGO Bootcamp Application</fullName>
                </value>
                <value>
                    <fullName>Leadership Certificate Sign-up</fullName>
                </value>
                <value>
                    <fullName>Leadership Fundamentals Application</fullName>
                </value>
                <value>
                    <fullName>Intergroup Dialogue Interest</fullName>
                </value>
                <value>
                    <fullName>Request for Overloading/Underloading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>NUSNET_ID__c</fullName>
        <externalId>true</externalId>
        <label>NUSNET ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/CaseDetailController.cls
public class CaseDetailController extends CommunityControllerBase{

    public Case c {set; get;}
    public Contact contact {set; get;}
    public Attachment attachment {set; get;}
    // public List<Case_Conversation__c> caseConversations {set; get;}
    //public Case_Conversation__c caseConversation {set; get;}
    public CaseComment caseComment {set; get;}
    public List<CaseComment> caseComments {set; get;}
    public List<Attachment> attHistory {set; get;}

    public Attachment humanSubjectAttachment {set; get;}
    public Attachment rescueAttachment {set; get;}
    public Attachment chserAttchment {set; get;}
    public Attachment participantAttachment {set; get;}
    public Attachment informedAttachment {set; get;}
    public Attachment fieldworkAttachment {set; get;}

    private final String humanSubject = 'humanSubject';
    private final String rescue = 'rescue';
    private final String chser = 'chser';
    private final String participant = 'participant';
    private final String informed = 'informed';
    private final String fieldwork = 'fieldwork';
    
    private Map<String, String> params;
    
    public CaseDetailController(){
        params = getParameters();

        if(String.isNotEmpty(params.get('error'))){
            showErrorMessage(params.get('error'));
        }

        c = [select Id,Department__c,Sub_Department__c,CaseNumber,Status,Type_of_Enquiry__c,Description,ContactId,Approval_Status__c from Case where Id =: params.get('cid') and ContactId =: ContactID];
        contact = [select Id,Name,Student_Identity__c,Email,NUSNET_ID__c from Contact where Id =: c.ContactId];
        attHistory = [select Id,Name,CreatedBy.Name from Attachment where ParentId =: c.Id order by CreatedDate desc, Name];
        
        loadConversations();
        loadCaseComments();
        
        attachment = new Attachment();
        //caseConversation = new Case_Conversation__c();
        caseComment = new CaseComment();

        humanSubjectAttachment = new Attachment();
        rescueAttachment = new Attachment();
        chserAttchment = new Attachment();
        participantAttachment = new Attachment();
        informedAttachment = new Attachment();
        fieldworkAttachment = new Attachment();
    }
    
    public void loadCaseComments(){
        caseComments = [select CommentBody, IsPublished, ParentId, CreatedById, CreatedDate, IsDeleted from CaseComment where ParentId =: c.Id and IsDeleted = false order by CreatedDate DESC];
    }
    
    public void loadConversations(){
        //caseConversations = [select Id,Name,Email__c,Message__c,Sender__c,Case__c from Case_Conversation__c where Case__c =: c.Id order by CreatedDate DESC];
    }
    
    public PageReference save(){
        Savepoint sp = Database.setSavepoint();

        // update case;
        try{
            update c;
        }catch(Exception e){
            Database.rollback(sp);
            this.showErrorMessage(e.getMessage());
        }

        // insert attachment
        try{
            if(attachment.Body != null){
                attachment.ParentId = c.Id;
                insert attachment;
            }
        }catch(Exception e){
            showErrorMessage('Upload attachment failed : ' + e.getMessage());
        }finally {
            attachment = new Attachment();
        }

        // insert human subject attachment
        if(!insertAttachment(sp, c, humanSubjectAttachment, humanSubject)){
            return error('Error upload human subjects attachment');
        }

        // insert rescue attachment
        if(!insertAttachment(sp,c,rescueAttachment, rescue)){
            return error('error upload rescue attachment');
        }

        // insert chser attchment
        if(!insertAttachment(sp, c, chserAttchment, chser)){
            return error('error upload chser attachment');
        }

        // insert participant attachment
        if(!insertAttachment(sp,c,participantAttachment, participant)){
            return error('error upload participant attachment');
        }

        // insert informed attachment
        if(!insertAttachment(sp, c, informedAttachment, informed)){
            return error('error upload informed attachment');
        }

        // insert fieldwork attachment
        if(!insertAttachment(sp, c, fieldworkAttachment, fieldwork)){
            return error('error upload fieldwork attachment');
        }

        try{
            if(String.isNotEmpty(caseComment.CommentBody)){
                caseComment.IsPublished = false;
                caseComment.ParentId = c.Id;
                
                insert caseComment;
            }
            
            return toCaseView();
        }catch(Exception e){
            showErrorMessage('Update Case Error : ' + e.getMessage());
        }Finally{
            caseComment = new CaseComment();
        }
        
        return null;
    }
    
    public void saveConversation(){
        //try{
        //    if(String.isNotBlank(caseConversation.Message__c)){
        //        caseConversation.Case__c = c.Id;
        //        caseConversation.Sender__c = contact.Name;
        //        caseConversation.Email__c = contact.Email;
        //        
        //        insert caseConversation;
        //        
        //        loadConversations();
        //        caseConversation = new Case_Conversation__c();
        //    }    
        //}catch(Exception e){
        //    showErrorMessage(e.getMessage());
       // }
    }

    private Boolean insertAttachment(Savepoint sp, Case c, Attachment att, String type){
        Boolean boo = true;

        if(att.Body != null){
            try{
                att.ParentId = c.Id;
                att.Name = attachmentFileName(att.Name, type);

                insert att;
            }catch(Exception e){
                Database.rollback(sp);
                this.showErrorMessage(type + ' error : ' + e.getMessage());
                boo = false;
            }finally {
                att = new Attachment();
            }
        }

        return boo;
    }

    private String attachmentFileName(String filename, String type){
        String name = '';
        Datetime dt = System.now();
        String timeString = dt.format('HHmmss');
        String dateString = dt.format('ddMMyyyy');

        if(type.equals(humanSubject)){
            name = 'Certificate.';
        }else if(type.equals(rescue)){
            name = 'RESCUE.';
        }else if(type.equals(chser)){
            name = 'CHSER.';
        }else if(type.equals(participant)){
            name = 'PIS.';
        }else if(type.equals(informed)){
            name = 'ICF.';
        }else if(type.equals(fieldwork)){
            name = 'FSP.';
        }

        if(String.isNotEmpty(name)){
            name += dateString + '.' + timeString + '.' + filename;
        }

        return name;
    }

    private PageReference error(String error){
        PageReference pr = Page.CaseDetail;
        pr.setRedirect(true);
        pr.getParameters().put('error', error);
        pr.getParameters().put('cid', params.get('cid'));

        return pr;
    }
    
    public PageReference cancel(){
        return toCaseView();
    }
    
    private PageReference toCaseView(){
        PageReference pr = Page.CaseView;
        pr.setRedirect(true);
        return pr;
    }
}