unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub  Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student Affairs</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Change Of Major</fullName>
                </value>
                <value>
                    <fullName>New Semester</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Experiential Opportunities</fullName>
                </value>
                <value>
                    <fullName>Fellowships and Graduate School</fullName>
                </value>
                <value>
                    <fullName>Leadership Development</fullName>
                </value>
                <value>
                    <fullName>RC Executives</fullName>
                </value>
                <value>
                    <fullName>Reg</fullName>
                </value>
                <value>
                    <fullName>VR</fullName>
                </value>
                <value>
                    <fullName>REC</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                    <isActive>false</isActive>
                    <label>Registry</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_Of_Enquiry__c</fullName>
        <label>Type of Enquiry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request for Transcripts</fullName>
                </value>
                <value>
                    <fullName>NS Deferment Letter</fullName>
                </value>
                <value>
                    <fullName>Request for Vice Rector Note</fullName>
                </value>
                <value>
                    <fullName>Summer Language Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Five Year Programme with Lee Kuan Yew School of Public Policy</fullName>
                </value>
                <value>
                    <fullName>Independent Reading and Research (IRR) Module Registration Form</fullName>
                </value>
                <value>
                    <fullName>Capstone Module Proposal Form</fullName>
                </value>
                <value>
                    <fullName>Request for Student Status Letter (Additional remarks needed)</fullName>
                </value>
                <value>
                    <fullName>Modules Add/Drop</fullName>
                </value>
                <value>
                    <fullName>2MC IRR/ 5MC Special Project</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Request for Change of Major/Minor</fullName>
                </value>
                <value>
                    <fullName>Request for Letter of Residence</fullName>
                </value>
                <value>
                    <fullName>Summer Independent Research</fullName>
                </value>
                <value>
                    <fullName>Summer Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Social Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Research</fullName>
                </value>
                <value>
                    <fullName>REC Form Submission</fullName>
                </value>
                <value>
                    <fullName>Leadership Ethics Application</fullName>
                </value>
                <value>
                    <fullName>NGO Bootcamp Application</fullName>
                </value>
                <value>
                    <fullName>Leadership Certificate Sign-up</fullName>
                </value>
                <value>
                    <fullName>Leadership Fundamentals Application</fullName>
                </value>
                <value>
                    <fullName>Intergroup Dialogue Interest</fullName>
                </value>
                <value>
                    <fullName>Request for Overloading/Underloading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Graduation_Year__c</fullName>
        <label>Graduation Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/SIR_Academic_Coursework__c.object
<CustomObject>
    <fields>
        <fullName>Summer_Independent_Research__c</fullName>
        <label>Summer Independent Research</label>
        <referenceTo>Summer_Independent_Research__c</referenceTo>
        <relationshipLabel>SIR Academic Courseworks</relationshipLabel>
        <relationshipName>SIR_Academic_Courseworks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SIR Academic Coursework</label>
    <nameField>
        <displayFormat>SIRAC-{0000000000}</displayFormat>
        <label>SIR Academic Coursework ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SIR Academic Courseworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Summer_Independent_Research__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Adviser__c</fullName>
        <label>Academic Advisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Background__c</fullName>
        <label>Background and Rationale</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>CAP__c</fullName>
        <label>CAP (non-freshmen only)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Summer Independent Researchs</relationshipLabel>
        <relationshipName>Summer_Independent_Researchs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Summer Independent Research</relationshipLabel>
        <relationshipName>Summer_Independent_Researchs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deliverables__c</fullName>
        <label>Deliverables</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Describe__c</fullName>
        <label>Describe</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Graduation_Year__c</fullName>
        <label>Graduation Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location(s)</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Major</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>List_Of_Major</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Materials and Methods</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Potential_Hurdle__c</fullName>
        <label>Potential Hurdles</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Abstract__c</fullName>
        <label>Project Abstract</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project_Co_Supervisor_Email__c</fullName>
        <label>Project Co Supervisor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Co_Supervisor__c</fullName>
        <label>Project Co-Supervisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Supervisor_Email__c</fullName>
        <label>Project Supervisor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Supervisor__c</fullName>
        <label>Project Supervisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Title__c</fullName>
        <label>Project Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Summer Independent Research</label>
    <nameField>
        <displayFormat>SIR-{0000000000}</displayFormat>
        <label>Summer Independent Research ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summer Independent Researchs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/SummerIndependentResearchController.cls
public class SummerIndependentResearchController extends CommunityControllerBase{

    public Summer_Independent_Research__c sir {set; get;}
    public List<SIR_Academic_Coursework__c> sirac {set; get;}
    //public String today {set;get;}
    public String indexString {set; get;}
    public Attachment budgetAttachment {set; get;}
    public Attachment transcriptAttachment {set; get;}
    public Attachment cvAttachment {set; get;}
    
    private Case c;
    private Contact contact;
    private List<SIR_Academic_Coursework__c> siracDeleted;
    private Map<String, String> params;
    
    public SummerIndependentResearchController(){
        params = this.getParameters();
        
        contact = [select Id,Name,Major__c,Graduation_Year__c from Contact where Id =: ContactID];
        siracDeleted = new List<SIR_Academic_Coursework__c>();
        
        budgetAttachment = new Attachment();
        transcriptAttachment = new Attachment();
        cvAttachment = new Attachment();
        
        if(params.get('status') == 'new'){
            //today = Datetime.now().format('dd MMMM yyyy');
            
            sir = new Summer_Independent_Research__c();
            sir.Full_Name__c = contact.Name;
            sir.Graduation_Year__c = contact.Graduation_Year__c;
            sir.Major__c = contact.Major__c;
            sir.Date__c = System.today();
            sir.Contact__c = contact.Id;
            
            sirac = new List<SIR_Academic_Coursework__c>();
            sirac.add(new SIR_Academic_Coursework__c());
            
            c = new Case();
            c.ContactId = contact.Id;
            c.Department__c = params.get('department');
            c.Type_Of_Enquiry__c = params.get('toe');
            c.RecordTypeId = [select Id from RecordType where Name =: params.get('toe')].Id;
            if(params.get('subdepartment') != 'null'){
                c.Sub_Department__c = params.get('subdepartment');    
            }            
        }else{
            sir = [select Id,Name,Case__c,Contact__c,Date__c,Full_Name__c,Graduation_Year__c,Major__c,CAP__c,Academic_Adviser__c,Project_Supervisor__c,Project_Supervisor_Email__c,Project_Co_Supervisor__c,Project_Co_Supervisor_Email__c,Project_Title__c,Background__c,Budget__c,Deliverables__c,Describe__c,Description__c,Location__c,Method__c,Potential_Hurdle__c,Project_Abstract__c,References__c,Research_Permit__c,Seeking_Answers__c,Special_Circumstances__c,Timeline__c,Hypothesis__c,Central_Research__c from Summer_Independent_Research__c where Id =: params.get('sid')];
            sirac = [select Id,Name,Course__c,Institution__c,Dates_of_Study_Start__c,Dates_of_Study_End__c,Grade_Received__c from SIR_Academic_Coursework__c where Summer_Independent_Research__c =: sir.Id];
            
            Datetime dt = datetime.newInstance(sir.Date__c.Year(), sir.Date__c.Month(), sir.Date__c.Day());
            //today = dt.format('dd MMMM yyyy');
        }
    }
    
    public void addRow(){
        sirac.add(new SIR_Academic_Coursework__c());
    }
    
    public void deleteRow(){
        Integer index = Integer.valueOf(indexString) - 1;
        
        SIR_Academic_Coursework__c dataDelete = sirac.get(index);
        sirac.remove(index);
        
        if(dataDelete.Summer_Independent_Research__c != null){
            siracDeleted.add(dataDelete);    
        }
    }
    
    public PageReference cancel(){
        return redirectToCaseView();
    }
    
    public PageReference save(){
        List<SIR_Academic_Coursework__c> siracInsert = new List<SIR_Academic_Coursework__c>();
        
        if(params.get('status') == 'new'){
            c.Subject = params.get('toe');
            c.Status = 'Open';
            c.Origin = 'Web';
            c.Priority = 'High';
            c.setOptions(dmo);
            insert c;
            
            sir.Status__c = 'In Progress';
            sir.Case__c = c.Id;
            insert sir;
            
            if(budgetAttachment.Body != null){
                budgetAttachment.ParentId = sir.Id;
                insert budgetAttachment;   
                budgetAttachment.Body = null;
            }
            
            if(transcriptAttachment.Body != null){
                transcriptAttachment.ParentId = sir.Id;
                insert transcriptAttachment;   
                transcriptAttachment.Body = null;
            }
            
            if(cvAttachment.Body != null){
                cvAttachment.ParentId = sir.Id;
                insert cvAttachment;   
                cvAttachment.Body = null;
            }
            
            for(SIR_Academic_Coursework__c data : sirac){
                if(String.isNotEmpty(data.Institution__c)){
                    data.Summer_Independent_Research__c = sir.Id;
                    siracInsert.add(data);
                }
            }
            
            insert sirac;
        }else{
            update sir;
            
            List<SIR_Academic_Coursework__c> siracUpdate = new List<SIR_Academic_Coursework__c>();
            
            for(SIR_Academic_Coursework__c data : sirac){
                if(data.Summer_Independent_Research__c == null){
                    siracInsert.add(data);
                }else{
                    siracUpdate.add(data);
                }
            }
            
            insert siracInsert;
            update siracUpdate;
        }
        
        if(siracDeleted.size() >= 0){
            delete siracDeleted;
        }

        return redirectToCaseView();
    }
}