unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub  Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student Affairs</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Change Of Major</fullName>
                </value>
                <value>
                    <fullName>New Semester</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Experiential Opportunities</fullName>
                </value>
                <value>
                    <fullName>Fellowships and Graduate School</fullName>
                </value>
                <value>
                    <fullName>Leadership Development</fullName>
                </value>
                <value>
                    <fullName>RC Executives</fullName>
                </value>
                <value>
                    <fullName>Reg</fullName>
                </value>
                <value>
                    <fullName>VR</fullName>
                </value>
                <value>
                    <fullName>REC</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                    <isActive>false</isActive>
                    <label>Registry</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_Of_Enquiry__c</fullName>
        <label>Type of Enquiry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request for Transcripts</fullName>
                </value>
                <value>
                    <fullName>NS Deferment Letter</fullName>
                </value>
                <value>
                    <fullName>Request for Vice Rector Note</fullName>
                </value>
                <value>
                    <fullName>Summer Language Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Five Year Programme with Lee Kuan Yew School of Public Policy</fullName>
                </value>
                <value>
                    <fullName>Independent Reading and Research (IRR) Module Registration Form</fullName>
                </value>
                <value>
                    <fullName>Capstone Module Proposal Form</fullName>
                </value>
                <value>
                    <fullName>Request for Student Status Letter (Additional remarks needed)</fullName>
                </value>
                <value>
                    <fullName>Modules Add/Drop</fullName>
                </value>
                <value>
                    <fullName>2MC IRR/ 5MC Special Project</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Request for Change of Major/Minor</fullName>
                </value>
                <value>
                    <fullName>Request for Letter of Residence</fullName>
                </value>
                <value>
                    <fullName>Summer Independent Research</fullName>
                </value>
                <value>
                    <fullName>Summer Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Social Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Research</fullName>
                </value>
                <value>
                    <fullName>REC Form Submission</fullName>
                </value>
                <value>
                    <fullName>Leadership Ethics Application</fullName>
                </value>
                <value>
                    <fullName>NGO Bootcamp Application</fullName>
                </value>
                <value>
                    <fullName>Leadership Certificate Sign-up</fullName>
                </value>
                <value>
                    <fullName>Leadership Fundamentals Application</fullName>
                </value>
                <value>
                    <fullName>Intergroup Dialogue Interest</fullName>
                </value>
                <value>
                    <fullName>Request for Overloading/Underloading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active SEP</fullName>
                </value>
                <value>
                    <fullName>Active LOA</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dates_of_Study_End__c</fullName>
        <label>Dates of Study (End)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dates_of_Study_Start__c</fullName>
        <label>Dates of Study (Start)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grade_Received__c</fullName>
        <label>Grade Received</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CN-{00000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/SSR_Academic_Coursework__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dates_of_Study_End__c</fullName>
        <label>Dates of Study (End)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dates_of_Study_Start__c</fullName>
        <label>Dates of Study (Start)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grade_Received__c</fullName>
        <label>Grade Received</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summer_Science_Research__c</fullName>
        <label>Summer Science Research</label>
        <referenceTo>Summer_Science_Research__c</referenceTo>
        <relationshipLabel>SSR Academic Courseworks</relationshipLabel>
        <relationshipName>SSR_Academic_Courseworks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SSR Academic Coursework</label>
    <nameField>
        <displayFormat>SSRAC-{0000000000}</displayFormat>
        <label>SSR Academic Coursework ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SSR Academic Courseworks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Summer_Science_Research__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Adviser__c</fullName>
        <label>Academic Advisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAP__c</fullName>
        <label>CAP (Year 2 students only)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Summer Science Researchs</relationshipLabel>
        <relationshipName>Summer_Science_Researchs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class_Year__c</fullName>
        <label>Class Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Summer Science Research</relationshipLabel>
        <relationshipName>Summer_Science_Researchs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Describe__c</fullName>
        <label>Describe any other prior research</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>First_Choices_Description__c</fullName>
        <label>First Choices Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>First_Choices__c</fullName>
        <label>First Choices For SSR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Second_Choices_Description__c</fullName>
        <label>Second Choices Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Second_Choices__c</fullName>
        <label>Second Choices For SSR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Circumstances__c</fullName>
        <label>Special Circumstances</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Summer Science Research</label>
    <nameField>
        <displayFormat>SSR-{0000000000}</displayFormat>
        <label>Summer Science Research ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summer Science Researchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/SummerScienceResearchController.cls
public class SummerScienceResearchController extends CommunityControllerBase{
    
    public Summer_Science_Research__c ssr {set; get;}
    public List<SSR_Academic_Coursework__c> ssrac {set; get;}
    //public String today {set;get;}
    public String indexString {set; get;}
    
    private Case c;
    private Contact contact;
    private List<SSR_Academic_Coursework__c> ssracDeleted;
    private Map<String, String> params;
    
    public SummerScienceResearchController(){
        params = this.getParameters();
        
        contact = [select Id,Name,Current_Year__c from Contact where Id =: ContactID];
        ssracDeleted = new List<SSR_Academic_Coursework__c>();
        
        if(params.get('status') == 'new'){
            //today = Datetime.now().format('dd MMMM yyyy');
            
            ssr = new Summer_Science_Research__c();
            ssr.Student_Name__c = contact.Name;
            ssr.Class_Year__c = contact.Current_Year__c;
            ssr.Date__c = System.today();
            ssr.Contact__c = contact.Id;
            
            ssrac = new List<SSR_Academic_Coursework__c>();
            ssrac.add(new SSR_Academic_Coursework__c());
            
            c = new Case();
            c.ContactId = contact.Id;
            c.Department__c = params.get('department');
            c.Type_Of_Enquiry__c = params.get('toe');
            c.RecordTypeId = [select Id from RecordType where Name =: params.get('toe')].Id;
            if(params.get('subdepartment') != 'null'){
                c.Sub_Department__c = params.get('subdepartment');    
            }            
        }else{
            ssr = [select Id,Name,Case__c,Contact__c,Date__c,Student_Name__c,Academic_Adviser__c,Class_Year__c,CAP__c,First_Choices__c,Second_Choices__c,Describe__c,First_Choices_Description__c,Second_Choices_Description__c,Special_Circumstances__c from Summer_Science_Research__c where Id =: params.get('sid')];
            ssrac = [select Id,Name,Course__c,Institution__c,Dates_of_Study_Start__c,Dates_of_Study_End__c,Grade_Received__c from SSR_Academic_Coursework__c where Summer_Science_Research__c =: ssr.Id];
            
            Datetime dt = datetime.newInstance(ssr.Date__c.Year(), ssr.Date__c.Month(), ssr.Date__c.Day());
            //today = dt.format('dd MMMM yyyy');
        }
    }
    
    public void addRow(){
        ssrac.add(new SSR_Academic_Coursework__c());
    }
    
    public void deleteRow(){
        Integer index = Integer.valueOf(indexString) - 1;
        
        SSR_Academic_Coursework__c dataDelete = ssrac.get(index);
        ssrac.remove(index);
        
        if(dataDelete.Summer_Science_Research__c != null){
            ssracDeleted.add(dataDelete);    
        }
    }
    
    public PageReference cancel(){
        return redirectToCaseView();
    }
    
    public PageReference save(){
        List<SSR_Academic_Coursework__c> ssracInsert = new List<SSR_Academic_Coursework__c>();
        
        if(params.get('status') == 'new'){
            c.Subject = params.get('toe');
            c.Status = 'Open';
            c.Origin = 'Web';
            c.Priority = 'High';
            c.setOptions(dmo);
            insert c;
            
            ssr.Case__c = c.Id;
            ssr.Status__c = 'In Progress';
            insert ssr;
            
            for(SSR_Academic_Coursework__c data : ssrac){
                if(String.isNotEmpty(data.Institution__c)){
                    data.Summer_Science_Research__c = ssr.Id;
                    ssracInsert.add(data);
                }
            }
            
            insert ssrac;
        }else{
            update ssr;
            
            List<SSR_Academic_Coursework__c> ssracUpdate = new List<SSR_Academic_Coursework__c>();
            
            for(SSR_Academic_Coursework__c data : ssrac){
                if(data.Summer_Science_Research__c == null){
                    ssracInsert.add(data);
                }else{
                    ssracUpdate.add(data);
                }
            }
            
            insert ssracInsert;
            update ssracUpdate;
        }
        
        if(ssracDeleted.size() >= 0){
            delete ssracDeleted;
        }
        
        return redirectToCaseView();
    }
}