unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub  Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student Affairs</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Change Of Major</fullName>
                </value>
                <value>
                    <fullName>New Semester</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Experiential Opportunities</fullName>
                </value>
                <value>
                    <fullName>Fellowships and Graduate School</fullName>
                </value>
                <value>
                    <fullName>Leadership Development</fullName>
                </value>
                <value>
                    <fullName>RC Executives</fullName>
                </value>
                <value>
                    <fullName>Reg</fullName>
                </value>
                <value>
                    <fullName>VR</fullName>
                </value>
                <value>
                    <fullName>REC</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                    <isActive>false</isActive>
                    <label>Registry</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_Of_Enquiry__c</fullName>
        <label>Type of Enquiry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request for Transcripts</fullName>
                </value>
                <value>
                    <fullName>NS Deferment Letter</fullName>
                </value>
                <value>
                    <fullName>Request for Vice Rector Note</fullName>
                </value>
                <value>
                    <fullName>Summer Language Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Five Year Programme with Lee Kuan Yew School of Public Policy</fullName>
                </value>
                <value>
                    <fullName>Independent Reading and Research (IRR) Module Registration Form</fullName>
                </value>
                <value>
                    <fullName>Capstone Module Proposal Form</fullName>
                </value>
                <value>
                    <fullName>Request for Student Status Letter (Additional remarks needed)</fullName>
                </value>
                <value>
                    <fullName>Modules Add/Drop</fullName>
                </value>
                <value>
                    <fullName>2MC IRR/ 5MC Special Project</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Request for Change of Major/Minor</fullName>
                </value>
                <value>
                    <fullName>Request for Letter of Residence</fullName>
                </value>
                <value>
                    <fullName>Summer Independent Research</fullName>
                </value>
                <value>
                    <fullName>Summer Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Social Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Research</fullName>
                </value>
                <value>
                    <fullName>REC Form Submission</fullName>
                </value>
                <value>
                    <fullName>Leadership Ethics Application</fullName>
                </value>
                <value>
                    <fullName>NGO Bootcamp Application</fullName>
                </value>
                <value>
                    <fullName>Leadership Certificate Sign-up</fullName>
                </value>
                <value>
                    <fullName>Leadership Fundamentals Application</fullName>
                </value>
                <value>
                    <fullName>Intergroup Dialogue Interest</fullName>
                </value>
                <value>
                    <fullName>Request for Overloading/Underloading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Concurrent_Degree_Programme__c.object
<CustomObject>
    <fields>
        <fullName>Accomplishments__c</fullName>
        <label>Accomplishments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Awards__c</fullName>
        <label>Awards</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Concurrent Degree Programmes</relationshipLabel>
        <relationshipName>Concurrent_Degree_Programmes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Citizenship__c</fullName>
        <label>Citizenship</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Number__c</fullName>
        <label>Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Concurrent Degree Programmes</relationshipLabel>
        <relationshipName>Concurrent_Degree_Programmes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Degree_Programme__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Joint/dual degree programmes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>NUS Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Exchange_Programme_Semesters__c</fullName>
        <label>Exchange Programme Semesters</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>One Semester</fullName>
                </value>
                <value>
                    <fullName>Two Semesters</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exchange_Programme__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exchange Programme</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Answer__c</fullName>
        <label>The most urgent policy challenge</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matriculation__c</fullName>
        <label>Matriculation No.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Other_Information__c</fullName>
        <label>Other Information (If Any)</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Programme_Name__c</fullName>
        <label>The Programme Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Second_Answer__c</fullName>
        <label>The main strengths and weaknesses</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Special_Programme_Name__c</fullName>
        <label>Special Programme Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Programmes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Currently in any special programme</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Third_Answer__c</fullName>
        <label>The programme will help you</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Volunteer_Work__c</fullName>
        <label>Volunteer Work</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Concurrent Degree Programme</label>
    <nameField>
        <displayFormat>CDP-{0000000000}</displayFormat>
        <label>Concurrent Degree Programme ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concurrent Degree Programmes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ConcurrentDegreeProgrammeController.cls
public class ConcurrentDegreeProgrammeController extends CommunityControllerBase{
    public Concurrent_Degree_Programme__c cdp {set; get;}
    //public String today {set; get;}
    public Attachment gceAttachment {set; get;}
    public Attachment transacriptAttachment {set; get;}
    
    private Case c;
    private Contact contact;
    private Map<String, String> params;
    
    public ConcurrentDegreeProgrammeController(){
        params = this.getParameters();
        
        contact = [select Id,Student_Identity__c,Name,Gender__c,Phone,MobilePhone,Email,Birthdate from Contact where Id =: ContactID];
        
        if(params.get('status') == 'new'){
            //today = Datetime.now().format('dd MMMM yyyy');
            
            cdp = new Concurrent_Degree_Programme__c();
            cdp.Full_Name__c = contact.Name;
            cdp.Matriculation__c = contact.Student_Identity__c;
            cdp.Date_of_Birth__c = contact.Birthdate;
            cdp.Gender__c = contact.Gender__c;
            cdp.Contact_Number__c = contact.Phone;
            cdp.Mobile_Number__c = contact.MobilePhone;
            cdp.Email__c = contact.Email;
            cdp.Date__c = System.today();
            cdp.Contact__c = contact.Id;
            
            c = new Case();
            c.ContactId = contact.Id;
            c.Department__c = params.get('department');
            c.Type_Of_Enquiry__c = params.get('toe');
            c.RecordTypeId = [select Id from RecordType where Name =: params.get('toe')].Id;
            if(params.get('subdepartment') != 'null'){
                c.Sub_Department__c = params.get('subdepartment');    
            }            
        }else{
            //cdp = [select Id,Name,Case__c,Contact__c,Date__c,Exchange_Programme_Semesters__c,Full_Name__c,Matriculation__c,Citizenship__c,Gender__c,Contact_Number__c,Mobile_Number__c,Email__c,Exchange_Programme__c,Degree_Programme__c,Programme_Name__c,Special_Programmes__c,Special_Programme_Name__c,First_Answer__c,Second_Answer__c,Third_Answer__c,Education__c,Awards__c,Accomplishments__c,Volunteer_Work__c,Other_Information__c from Concurrent_Degree_Programme__c where Id =: params.get('cid')];
            
            Datetime dt = datetime.newInstance(cdp.Date__c.Year(), cdp.Date__c.Month(), cdp.Date__c.Day());
            //today = dt.format('dd MMMM yyyy');
        }

        gceAttachment = new Attachment();
        transacriptAttachment = new Attachment();
    }
    
    public PageReference cancel(){
        return redirectToCaseView();
    }
    
    public PageReference save(){
        if(params.get('status') == 'new'){
            c.Subject = params.get('toe');
            c.Status = 'Open';
            c.Origin = 'Web';
            c.Priority = 'High';
            c.setOptions(dmo);
            insert c;
            
            cdp.Case__c = c.Id;
            insert cdp;
            
            if(gceAttachment.Body != null){
                gceAttachment.ParentId = cdp.Id;
                gceAttachment.Name = 'GCE_' + gceAttachment.Name;
                insert gceAttachment;
                
                gceAttachment.Body = null;
            }
            
            if(transacriptAttachment.Body != null){
                transacriptAttachment.ParentId = cdp.Id;
                transacriptAttachment.Name = 'GCE_' + transacriptAttachment.Name;
                insert transacriptAttachment;
                
                transacriptAttachment.Body = null;
            }
        }else{
            update cdp;
        }
        
        return redirectToCaseView();
    }
}