unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_Of_Enquiry__c</fullName>
        <label>Type of Enquiry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request for Transcripts</fullName>
                </value>
                <value>
                    <fullName>NS Deferment Letter</fullName>
                </value>
                <value>
                    <fullName>Request for Vice Rector Note</fullName>
                </value>
                <value>
                    <fullName>Summer Language Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Five Year Programme with Lee Kuan Yew School of Public Policy</fullName>
                </value>
                <value>
                    <fullName>Independent Reading and Research (IRR) Module Registration Form</fullName>
                </value>
                <value>
                    <fullName>Capstone Module Proposal Form</fullName>
                </value>
                <value>
                    <fullName>Request for Student Status Letter (Additional remarks needed)</fullName>
                </value>
                <value>
                    <fullName>Modules Add/Drop</fullName>
                </value>
                <value>
                    <fullName>2MC IRR/ 5MC Special Project</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Request for Change of Major/Minor</fullName>
                </value>
                <value>
                    <fullName>Request for Letter of Residence</fullName>
                </value>
                <value>
                    <fullName>Summer Independent Research</fullName>
                </value>
                <value>
                    <fullName>Summer Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Social Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Research</fullName>
                </value>
                <value>
                    <fullName>REC Form Submission</fullName>
                </value>
                <value>
                    <fullName>Leadership Ethics Application</fullName>
                </value>
                <value>
                    <fullName>NGO Bootcamp Application</fullName>
                </value>
                <value>
                    <fullName>Leadership Certificate Sign-up</fullName>
                </value>
                <value>
                    <fullName>Leadership Fundamentals Application</fullName>
                </value>
                <value>
                    <fullName>Intergroup Dialogue Interest</fullName>
                </value>
                <value>
                    <fullName>Request for Overloading/Underloading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Change_Of_Major__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Request for Change of Major/Minor</relationshipLabel>
        <relationshipName>Change_Of_Majors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>List_Of_Major</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Minor__c</fullName>
        <label>Current Minor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>List_Of_Major</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Change Of Major</label>
    <nameField>
        <displayFormat>CM-{0000000000}</displayFormat>
        <label>Change Of Major ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Of Majors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_of_Course__c</fullName>
        <label>Length of Course</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matric_Year__c</fullName>
        <label>Matric Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minor__c</fullName>
        <label>Current Minor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NRIC__c</fullName>
        <label>NRIC/FIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_College__c</fullName>
        <label>Residential College</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Residential_College__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Residential College History</relationshipLabel>
        <relationshipName>Residential_Colleges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_From__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_To__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Residential_College_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residential College Name</label>
        <referenceTo>Residential_College_Master__c</referenceTo>
        <relationshipLabel>Residential Colleges</relationshipLabel>
        <relationshipName>Residential_Colleges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suite_No__c</fullName>
        <label>Suite No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Residential College</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Residential College ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residential Colleges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ChangeOfMajorController.cls
public class ChangeOfMajorController extends CommunityControllerBase{
    
    public Contact contact {set; get;}
    public Case c {set; get;}
    public  Change_Of_Major__c com{set; get;}
    public List<Residential_College__c> rc {set; get;}
    public String residentialCollegeName {set; get;}
    //public String today {set; get;}
    public String currentMajor {set; get;}
    public String currentMinor {set; get;}
    public Boolean showMinor {set; get;}
    
    public List<SelectOption> hosMajorList {set; get;}
    public List<SelectOption> hosMinorList {set; get;}

    private Map<String, String> params;
    
    public ChangeOfMajorController(){
        params = this.getParameters();
        
        contact = [select Id,Name,Student_Identity__c,Email,Matric_Year__c,NRIC__c,Current_Year__c,Length_of_Course__c,Major__c,Minor__c from Contact where Id =: ContactID];
        rc = [select Id,Name,Date_To__c,Date_From__c,Suite_No__c,Residential_College_Master__r.Name from Residential_College__c where Contact__c =: contact.Id and Date_To__c = null limit 1];
        
        if(rc.size() > 0){
            residentialCollegeName = rc.get(0).Residential_College_Master__r.Name;
        }else{
            residentialCollegeName = '-';
        }

        if(params.get('status') == 'new'){
            //today = Datetime.now().format('dd MMMM yyyy');
            
            com = new Change_Of_Major__c();
            com.Date__c = System.today();
            com.Contact__c = contact.Id;
            com.Current_Major__c = contact.Major__c;
            com.Current_Minor__c = contact.Minor__c;
            
            currentMajor = com.Current_Major__c;
            currentMinor = com.Current_Minor__c;

            if(String.isNotEmpty(currentMinor)){
                showMinor = true;
            }else{
                showMinor = false;
            }
            
            c = new Case();
            c.ContactId = contact.Id;
            c.Department__c = params.get('department');
            c.Type_Of_Enquiry__c = params.get('toe');
            c.RecordTypeId = [select Id from RecordType where Name = 'Change of Major'].Id;
            if(params.get('subdepartment') != 'null'){
                c.Sub_Department__c = params.get('subdepartment');    
            }
            
            hosMajorList = new List<SelectOption>();
            hosMinorList = new List<SelectOption>();
            
            hosMajorList.add(new SelectOption('', '--None--'));
            hosMinorList.add(new SelectOption('', '--None--'));
            
            for(User user : [select Name from User where Type__c includes('Head of Study')]){
                hosMajorList.add(new SelectOption(user.Id, user.Name));
                hosMinorList.add(new SelectOption(user.Id, user.Name));
            }
        }else{
            com = [select Id,Name,Case__c,Contact__c,Current_Major__c,Current_Minor__c,New_Major__c,New_Minor__c,Change_Drop_Minor__c from Change_Of_Major__c where Id =: params.get('cid')];
            c = [select Id,ContactId,Department__c,Type_Of_Enquiry__c,RecordTypeId,Sub_Department__c,Subject,Status,Origin,Priority,Start_Date__c,End_Date__c from Case where Id =: com.Case__c];
            
            Datetime dt = datetime.newInstance(com.Date__c.Year(), com.Date__c.Month(), com.Date__c.Day());
            //today = dt.format('dd MMMM yyyy');
            
            currentMajor = com.Current_Major__c;
            currentMinor = com.Current_Minor__c;
        }
    }
    
    public PageReference cancel(){
        return redirectToCaseView();
    }
    
    public PageReference save(){
        if(params.get('status') == 'new'){
            c.Subject = params.get('toe');
            c.Status = 'Open';
            c.Origin = 'Web';
            c.Priority = 'High';
            c.setOptions(dmo);
            insert c;
            
            com.Case__c = c.Id;
            
            if(String.isEmpty(com.Major_Head_Of_Study__c)){
                com.Major_Head_Of_Study__c = null;
            }
            
            if(String.isEmpty(com.Minor_Head_Of_Study__c)){
                com.Minor_Head_Of_Study__c = null;
            }
            
            insert com;
        }else{
            update com;
        }
        
        return redirectToCaseView();
    }

}