unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>REC_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supervisor</label>
        <lookupFilter>
            <active>false</active>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub  Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student Affairs</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Change Of Major</fullName>
                </value>
                <value>
                    <fullName>New Semester</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Experiential Opportunities</fullName>
                </value>
                <value>
                    <fullName>Fellowships and Graduate School</fullName>
                </value>
                <value>
                    <fullName>Leadership Development</fullName>
                </value>
                <value>
                    <fullName>RC Executives</fullName>
                </value>
                <value>
                    <fullName>Reg</fullName>
                </value>
                <value>
                    <fullName>VR</fullName>
                </value>
                <value>
                    <fullName>REC</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                    <isActive>false</isActive>
                    <label>Registry</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_Of_Enquiry__c</fullName>
        <label>Type of Enquiry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request for Transcripts</fullName>
                </value>
                <value>
                    <fullName>NS Deferment Letter</fullName>
                </value>
                <value>
                    <fullName>Request for Vice Rector Note</fullName>
                </value>
                <value>
                    <fullName>Summer Language Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Five Year Programme with Lee Kuan Yew School of Public Policy</fullName>
                </value>
                <value>
                    <fullName>Independent Reading and Research (IRR) Module Registration Form</fullName>
                </value>
                <value>
                    <fullName>Capstone Module Proposal Form</fullName>
                </value>
                <value>
                    <fullName>Request for Student Status Letter (Additional remarks needed)</fullName>
                </value>
                <value>
                    <fullName>Modules Add/Drop</fullName>
                </value>
                <value>
                    <fullName>2MC IRR/ 5MC Special Project</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Request for Change of Major/Minor</fullName>
                </value>
                <value>
                    <fullName>Request for Letter of Residence</fullName>
                </value>
                <value>
                    <fullName>Summer Independent Research</fullName>
                </value>
                <value>
                    <fullName>Summer Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Social Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Research</fullName>
                </value>
                <value>
                    <fullName>REC Form Submission</fullName>
                </value>
                <value>
                    <fullName>Leadership Ethics Application</fullName>
                </value>
                <value>
                    <fullName>NGO Bootcamp Application</fullName>
                </value>
                <value>
                    <fullName>Leadership Certificate Sign-up</fullName>
                </value>
                <value>
                    <fullName>Leadership Fundamentals Application</fullName>
                </value>
                <value>
                    <fullName>Intergroup Dialogue Interest</fullName>
                </value>
                <value>
                    <fullName>Request for Overloading/Underloading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Degree_Name__c</fullName>
        <label>Current Degree Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Course__c</fullName>
        <label>Length of Course</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matric_Year__c</fullName>
        <label>Matric Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minor__c</fullName>
        <label>Current Minor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NRIC__c</fullName>
        <label>NRIC/FIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NUSNET_ID__c</fullName>
        <externalId>true</externalId>
        <label>NUSNET ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Faculty</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Head of Study</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dean of Student</fullName>
                </value>
                <value>
                    <fullName>Faculty Advisor</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Divisional Director</fullName>
                </value>
                <value>
                    <fullName>Head of Study</fullName>
                </value>
                <value>
                    <fullName>Vice Rector</fullName>
                </value>
                <value>
                    <fullName>RC Exec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/RECFormController.cls
public class RECFormController extends CommunityControllerBase{

    //public BusinessHours BH  {set; get;}
    public Contact contact {set; get;}
    public Case c {set; get;}
    public Attachment humanSubjectAttachment {set; get;}
    public Attachment rescueAttachment {set; get;}
    public Attachment chserAttchment {set; get;}
    public Attachment participantAttachment {set; get;}
    public Attachment informedAttachment {set; get;}
    public Attachment fieldworkAttachment {set; get;}

    public String supervisorID {set; get;}
    public String headOfStudyID {set; get;}
    public List<SelectOption> supervisorOptions {set; get;}
    public List<SelectOption> headOfStudyOptions {set; get;}

    private Map<String,String> params;

    private final String humanSubject = 'humanSubject';
    private final String rescue = 'rescue';
    private final String chser = 'chser';
    private final String participant = 'participant';
    private final String informed = 'informed';
    private final String fieldwork = 'fieldwork';

    public RECFormController(){
        params = this.getParameters();

        if(String.isNotEmpty(params.get('error'))){
            this.showErrorMessage(params.get('error'));
        }

        contact = [
            select
                Id,Name,Student_Identity__c,Email,Matric_Year__c,NRIC__c,Current_Year__c,Degree_Name__c,Length_of_Course__c,Major__c,Minor__c,NUSNET_ID__c
            from Contact
            where Id =: ContactID
        ];

        c = new Case();
        c.ContactId = contact.Id;
        c.Department__c = params.get('department');
        c.Type_Of_Enquiry__c = params.get('toe');
        c.RecordTypeId = [select Id from RecordType where Name = 'REC Form Submission'].Id;
        if(params.get('subdepartment') != 'null'){
            c.Sub_Department__c = params.get('subdepartment');
        }

        humanSubjectAttachment = new Attachment();
        rescueAttachment = new Attachment();
        chserAttchment = new Attachment();
        participantAttachment = new Attachment();
        informedAttachment = new Attachment();
        fieldworkAttachment = new Attachment();

        supervisorOptions = new List<SelectOption>();
        supervisorOptions.add(new SelectOption('none', '--None--'));
        //supervisorOptions.add(new SelectOption('005p0000001WTfC', 'Test Supervisor'));

        headOfStudyOptions = new List<SelectOption>();
        headOfStudyOptions.add(new SelectOption('none', '--None--'));
        //headOfStudyOptions.add(new SelectOption('005p0000001WTfH', 'Test Head of Study'));

        List<User> supervisorUsers = [select Id,Name,Type__c from User where Type__c includes('Supervisor')];
        for(User user : supervisorUsers){
            supervisorOptions.add(new SelectOption(user.Id, user.Name));
        }

        List<User> headOfStudyUsers = [select Id,Name,Type__c from User where Type__c includes('Head of Study')];
        for(User user : headOfStudyUsers){
            headOfStudyOptions.add(new SelectOption(user.Id, user.Name));
        }
    }

    public PageReference save(){
        // form validation
        if(supervisorID == null || supervisorID == 'none'){
            return error('Supervisor cannot be null!');
        }

        if(headOfStudyID == null || headOfStudyID == 'none'){
            return error('Head of Study cannot be null!');
        }

        if(humanSubjectAttachment.Body == null){
            return error('Human Subjects Training Certificate document cannot be null!');
        }

        Savepoint sp = Database.setSavepoint();
        
        //BH = [select id from businesshours where IsDefault=true limit 1];
        //Datetime maxDate1stLvlApproval = BusinessHours.Add(BH.Id, System.now(), 108000000); //108000000 (MilliSecond) = 3 days from created date

        c.Subject = params.get('toe');
        c.Status = 'Open';
        c.Origin = 'Web';
        c.Priority = 'High';
        c.REC_Supervisor__c = supervisorID;
        c.REC_Head_of_Study__c = headOfStudyID;
        c.Approval_Status__c = 'Pending Supervisor';
        //c.Max_Datetime_1st_Level_Approved__c = maxDate1stLvlApproval;
        //c.Queue_taking_ownership_datetime__c = maxDate1stLvlApproval;
        c.setOptions(dmo);
        insert c;

        REC_Form_Submitted__c rec = new REC_Form_Submitted__c();
        rec.Case__c = c.Id;
        rec.Contact__c = c.ContactId;
        rec.Supervisor__c = c.REC_Supervisor__c;
        rec.Head_of_Study__c = c.REC_Head_of_Study__c;
        insert rec;

        
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setComments('Submitted for approval. Please approve.');
        req.setObjectId(c.Id);
        Approval.process(req);
        

        // insert human subject attachment
        if(!insertAttachment(sp, c, humanSubjectAttachment, humanSubject)){
            return error('Error upload human subjects attachment');
        }

        // insert rescue attachment
        if(!insertAttachment(sp,c,rescueAttachment, rescue)){
            return error('error upload rescue attachment');
        }

        // insert chser attchment
        if(!insertAttachment(sp, c, chserAttchment, chser)){
            return error('error upload chser attachment');
        }

        // insert participant attachment
        if(!insertAttachment(sp,c,participantAttachment, participant)){
            return error('error upload participant attachment');
        }

        // insert informed attachment
        if(!insertAttachment(sp, c, informedAttachment, informed)){
            return error('error upload informed attachment');
        }

        // insert fieldwork attachment
        if(!insertAttachment(sp, c, fieldworkAttachment, fieldwork)){
            return error('error upload fieldwork attachment');
        }

        return cancel();
    }

    private Boolean insertAttachment(Savepoint sp, Case c, Attachment att, String type){
        Boolean boo = true;

        if(att.Body != null){
            try{
                att.ParentId = c.Id;
                att.Name = attachmentFileName(att.Name, type);

                insert att;
            }catch(Exception e){
                Database.rollback(sp);
                this.showErrorMessage(type + ' error : ' + e.getMessage());
                boo = false;
            }finally {
                att = new Attachment();
            }
        }

        return boo;
    }

    private PageReference error(String error){
        String url = '/RECForm?department='+params.get('department')+'&subdepartment='+params.get('subdepartment')+'&toe='+params.get('toe')+'&status=new';
        PageReference pr = new PageReference(url);
        pr.setRedirect(true);
        pr.getParameters().put('error', error);

        return pr;
    }

    public PageReference cancel(){
        PageReference pr = Page.CaseView;
        pr.setRedirect(true);
        return pr;
    }

    private String attachmentFileName(String filename, String type){
        String name = '';
        Datetime dt = System.now();
        String timeString = dt.format('HHmmss');
        String dateString = dt.format('ddMMyyyy');

        if(type.equals(humanSubject)){
            name = 'Certificate.';
        }else if(type.equals(rescue)){
            name = 'RESCUE.';
        }else if(type.equals(chser)){
            name = 'CHSER.';
        }else if(type.equals(participant)){
            name = 'PIS.';
        }else if(type.equals(informed)){
            name = 'ICF.';
        }else if(type.equals(fieldwork)){
            name = 'FSP.';
        }

        if(String.isNotEmpty(name)){
            name += dateString + '.' + timeString + '.' + filename;
        }

        return name;
    }
}