unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student Services</fullName>
                </value>
                <value>
                    <fullName>Vice Rectors</fullName>
                </value>
                <value>
                    <fullName>Dean of Students</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                </value>
                <value>
                    <fullName>Office of Financial Aid</fullName>
                </value>
                <value>
                    <fullName>Centre for International and Professional Experience</fullName>
                </value>
                <value>
                    <fullName>Residential College Offices</fullName>
                </value>
                <value>
                    <fullName>Research Ethics Committee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub  Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Student Affairs</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Change Of Major</fullName>
                </value>
                <value>
                    <fullName>New Semester</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Experiential Opportunities</fullName>
                </value>
                <value>
                    <fullName>Fellowships and Graduate School</fullName>
                </value>
                <value>
                    <fullName>Leadership Development</fullName>
                </value>
                <value>
                    <fullName>RC Executives</fullName>
                </value>
                <value>
                    <fullName>Reg</fullName>
                </value>
                <value>
                    <fullName>VR</fullName>
                </value>
                <value>
                    <fullName>REC</fullName>
                </value>
                <value>
                    <fullName>Registry</fullName>
                    <isActive>false</isActive>
                    <label>Registry</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_Of_Enquiry__c</fullName>
        <label>Type of Enquiry</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request for Transcripts</fullName>
                </value>
                <value>
                    <fullName>NS Deferment Letter</fullName>
                </value>
                <value>
                    <fullName>Request for Vice Rector Note</fullName>
                </value>
                <value>
                    <fullName>Summer Language Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Five Year Programme with Lee Kuan Yew School of Public Policy</fullName>
                </value>
                <value>
                    <fullName>Independent Reading and Research (IRR) Module Registration Form</fullName>
                </value>
                <value>
                    <fullName>Capstone Module Proposal Form</fullName>
                </value>
                <value>
                    <fullName>Request for Student Status Letter (Additional remarks needed)</fullName>
                </value>
                <value>
                    <fullName>Modules Add/Drop</fullName>
                </value>
                <value>
                    <fullName>2MC IRR/ 5MC Special Project</fullName>
                </value>
                <value>
                    <fullName>General Enquiry</fullName>
                </value>
                <value>
                    <fullName>Request for Change of Major/Minor</fullName>
                </value>
                <value>
                    <fullName>Request for Letter of Residence</fullName>
                </value>
                <value>
                    <fullName>Summer Independent Research</fullName>
                </value>
                <value>
                    <fullName>Summer Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Social Science Research</fullName>
                </value>
                <value>
                    <fullName>Summer Research</fullName>
                </value>
                <value>
                    <fullName>REC Form Submission</fullName>
                </value>
                <value>
                    <fullName>Leadership Ethics Application</fullName>
                </value>
                <value>
                    <fullName>NGO Bootcamp Application</fullName>
                </value>
                <value>
                    <fullName>Leadership Certificate Sign-up</fullName>
                </value>
                <value>
                    <fullName>Leadership Fundamentals Application</fullName>
                </value>
                <value>
                    <fullName>Intergroup Dialogue Interest</fullName>
                </value>
                <value>
                    <fullName>Request for Overloading/Underloading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Scholarship</fullName>
        <active>true</active>
        <businessProcess>Scholarship</businessProcess>
        <label>Scholarship</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Graduation_Year__c</fullName>
        <label>Graduation Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matric_Year__c</fullName>
        <label>Matric Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NUSNET_ID__c</fullName>
        <externalId>true</externalId>
        <label>NUSNET ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name_of_Head_of_Studies__c</fullName>
        <inlineHelpText>or Academic Advisor if undeclared major</inlineHelpText>
        <label>Name of Head of Studies</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_College__c</fullName>
        <label>Residential College</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Faculty</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Head of Study</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Student</fullName>
        <active>true</active>
        <description>Student information</description>
        <label>Student</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scholarships__c</fullName>
        <label>Scholarships</label>
        <referenceTo>Scholarships__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CN-{00000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Residential_College__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Residential College History</relationshipLabel>
        <relationshipName>Residential_Colleges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_From__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_To__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Suite_No__c</fullName>
        <label>Suite No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Residential College</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Residential College ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residential Colleges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Scholarships__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Scholarships</relationshipLabel>
        <relationshipName>Scholarships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Scholarship</relationshipLabel>
        <relationshipName>Scholarships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>none</fullName>
                </value>
                <value>
                    <fullName>Summer Academic Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Arts Scholarship</fullName>
                </value>
                <value>
                    <fullName>Summer Language Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Scholarships</label>
    <nameField>
        <displayFormat>SCID-{00000000}</displayFormat>
        <label>Award ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scholarships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/SummerScholarshipController.cls
public without sharing class SummerScholarshipController extends ControllerBase{
    public Contact student { get; set; }
    public Scholarships__c schShip { get; set; }
    public String summerSch { get; set; }
    public Course__c course1 { get; set; }
    public Course__c course2 { get; set; }
    public Course__c course3 { get; set; }
    public Course__c course4 { get; set; }
    public Course__c course5 { get; set; }
    public Residential_College__c rc {set; get;}
    public List<Course__c> courses {set; get;}
    public String indexString {set; get;}
    public Attachment attachment {set; get;}
    public String yearTitle {set; get;} 
    
    private String nid;

    public SummerScholarshipController(){
        nid = Apexpages.currentPage().getParameters().get('nid');
        student = [select id, accountId, firstName, lastName,Matric_Year__c, Residential_College__c, Name_of_Head_of_Studies__c,Student_Identity__c,Graduation_Year__c from contact where NUSNET_ID__c=:nid];
        rc = [select Id,Name,Date_To__c,Date_From__c,Suite_No__c from Residential_College__c where Contact__c =: student.Id and Date_To__c = null limit 1];
        
        yearTitle = Label.Year_Title;
        
        schShip = new Scholarships__c();
        course1 = new Course__c();
        course2 = new Course__c();
        course3 = new Course__c();
        course4 = new Course__c();
        course5 = new Course__c();
        
        courses = new List<Course__c>();
        courses.add(new Course__c());
    }
    
    public void addRow(){
        courses.add(new Course__c());
    }
    
    public void deleteRow(){
        Integer index = Integer.valueOf(indexString) - 1;
        courses.remove(index);
    }
    
    public PageReference submitData(){
        string department = Apexpages.currentPage().getParameters().get('department');
        string subdepartment = Apexpages.currentPage().getParameters().get('subdepartment');
        string toe = Apexpages.currentPage().getParameters().get('toe');
    
        Savepoint sp = Database.setSavepoint();
    
        try{
            if(nid != null){
                // student.Student_identity__c = sid;
                List<Contact> listStudent = [select id, accountId, firstName, lastName, Matric_Year__c,Residential_College__c, Name_of_Head_of_Studies__c from contact where NUSNET_ID__c=:nid];
                
                if(!listStudent.isEmpty()){
                    student = listStudent[0];
                }
                else{
                    //student.Student_identity__c = sid;
                    insert student;
                }
            }
            else{
                insert student;
            }
            
            if(summerSch != null){
                schShip.Type__c = summerSch;
            }
            
            Case newCase = new Case();
            newCase.ContactId = student.id;
            newCase.Department__c = department;
            newCase.Sub_Department__c = subdepartment;
            newCase.Type_Of_Enquiry__c = toe;
            newCase.RecordTypeId = [select Id from RecordType where Name = 'Scholarship'].Id;
            newCase.Subject = toe;
            newCase.Status = 'Open';
            newCase.Origin = 'Web';
            newCase.Priority = 'High';
            
            insert newCase;
            
            schShip.Student__c = student.id;
            schShip.Case__c = newCase.Id;
            insert schShip;
            
            if(attachment.Body != null){
                attachment.ParentId = schShip.Id;
                insert attachment;
                attachment.Body = null;
            }
            
            if(course1.Institution__c !=null && course1.course__c != null){
                course1.Scholarships__c = schShip.Id;
                insert course1;
            }
            if(course2.Institution__c !=null && course2.course__c != null){
                course2.Scholarships__c = schShip.Id;
                insert course2;
            }
            if(course3.Institution__c !=null && course3.course__c != null){
                course3.Scholarships__c = schShip.Id;
                insert course3;
            }
            if(course4.Institution__c !=null && course4.course__c != null){
                course4.Scholarships__c = schShip.Id;
                insert course4;
            }
            if(course5.Institution__c !=null && course5.course__c != null){
                course5.Scholarships__c = schShip.Id;
                insert course5;
            }
            
            for(Course__c c:courses){
            	if(c.Institution__c !=null && c.course__c != null){
                    c.Scholarships__c = schShip.Id;
                    insert c;
                }    
            }
            
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Data saved!'));
            
            return new PageReference('/CaseView?nid=' + nid); 
        }
        catch(DmlException e){
            Database.rollback(sp);

            System.debug('DmlException');
            System.debug(e.getMessage());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()+' at line '+e.getLineNumber()));

            return null;
        }
        catch(Exception e){
            Database.rollback(sp);

            System.debug('Exception');
            System.debug(e.getMessage());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()+' at line '+e.getLineNumber()));
            
            return null;
        }
    
        return cancel();
    }
    
    public PageReference cancel(){
        return new PageReference('/CaseView?nid=' + nid);
    }
}