unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>NUSNET_ID__c</fullName>
        <externalId>true</externalId>
        <label>NUSNET ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Parent_Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Sub Departments</relationshipLabel>
        <relationshipName>Departments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Type_of_Enquiry__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.Parent_Department__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Type of Enquiries</relationshipLabel>
        <relationshipName>Type_of_Enquiries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Type of Enquiry</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Type of Enquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/GeneralEnquiryController.cls
public class GeneralEnquiryController extends CommunityControllerBase{

    public List<Department__c> departments {set; get;}
    public List<Department__c> subDepartments {set; get;}
    public List<Type_of_Enquiry__c> toes {set; get;}
    
    public Contact contact {set; get;}
    
    public boolean showDepartment {set; get;}
    public boolean showSubDepartment {set; get;}
    public boolean showTypeOfEnquiry {set; get;}
    
    public String department {set; get;}
    public String subDepartment {set; get;}
    public String typeOfEnquiry {set; get;}
    
    public GeneralEnquiryController(){
        Map<String, String> params = getParameters();
        
        contact = [select Id,Name,Student_Identity__c,NUSNET_ID__c from Contact where Id =: ContactID];
        departments = [select Id,Name,Description__c from Department__c where Parent_Department__c = null and Active__c = true order by Name];
        toes = [select Id,Name,Link__c from Type_of_Enquiry__c];
        
        showDepartment = true;
        showSubDepartment = false;
        showTypeOfEnquiry = false;
    }
    
    public PageReference back(){
        return redirectToCaseView();
    }
    
    public void pickDepartment(){
        department = getParameters().get('department');
        
        subDepartments = [select Id,Name,Description__c from Department__c where Parent_Department__r.Name =: department and Active__c = true order by Name];
        
        showDepartment = false;
        showSubDepartment = true;
        showTypeOfEnquiry = false;
    }
    
    public void pickSubDepartment(){
        subDepartment = getParameters().get('subDepartment');
        
        System.debug('sd = ' +subDepartment);
        
        Department__c d = [select Id from Department__c where Name =: subDepartment order by Name];
        toes = [select Id,Name,Link__c from Type_of_Enquiry__c where Department__c =: d.Id and Active__c = true];
        
        showDepartment = false;
        showSubDepartment = false;
        showTypeOfEnquiry = true;
    }
    
    public void prevSubDepartment(){
        department = '';
        
        showDepartment = true;
        showSubDepartment = false;
        showTypeOfEnquiry = false;
    }
    
    public void prevTypeOfEnquiry(){
        subDepartment = '';
        
        showDepartment = false;
        showSubDepartment = true;
        showTypeOfEnquiry = false;
    }
}