unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_of_Course__c</fullName>
        <label>Length of Course</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matric_Year__c</fullName>
        <label>Matric Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NRIC__c</fullName>
        <label>NRIC/FIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NUSNET_ID__c</fullName>
        <externalId>true</externalId>
        <label>NUSNET ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Residential_College__c</fullName>
        <label>Residential College</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Semester 1</fullName>
                </value>
                <value>
                    <fullName>Semester 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Plan_Of_Study__c.object
<CustomObject>
    <fields>
        <fullName>Capstone_Advisor__c</fullName>
        <label>Capstone Advisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Plan Of Studies</relationshipLabel>
        <relationshipName>Plan_Of_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Faculty_Advisor__c</fullName>
        <label>Faculty Advisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Head_of_Studies__c</fullName>
        <label>Head of Studies for Major</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Of_Study__c</fullName>
        <label>Year of Study as of form submission</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Year_Of_Study</valueSetName>
        </valueSet>
    </fields>
    <label>Plan Of Study</label>
    <nameField>
        <displayFormat>POS-{0000000000}</displayFormat>
        <label>Plan Of Study ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Of Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Plan_Of_Study_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Extra_curricular__c</fullName>
        <label>Extra-curricular</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MC__c</fullName>
        <label>MC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Major Requirement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module_Name__c</fullName>
        <label>Module</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Of_Study__c</fullName>
        <label>Plan Of Study</label>
        <referenceTo>Plan_Of_Study__c</referenceTo>
        <relationshipLabel>Plan Of Study Details</relationshipLabel>
        <relationshipName>Plan_Of_Study_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Semester 1</fullName>
                </value>
                <value>
                    <fullName>Semester 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Plan Of Study Detail</label>
    <nameField>
        <displayFormat>POSD-{0000000000}</displayFormat>
        <label>POS Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Of Study Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Plan_Of_Study_Result__c.object
<CustomObject>
    <fields>
        <fullName>CAP__c</fullName>
        <label>Cumulative CAP</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Career_Planning__c</fullName>
        <label>Career Planning Recomendations</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Extra_Curricular__c</fullName>
        <label>Extra Curricular</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MC__c</fullName>
        <label>Cumulative MCs completed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Of_Study__c</fullName>
        <label>Plan Of Study</label>
        <referenceTo>Plan_Of_Study__c</referenceTo>
        <relationshipLabel>Plan Of Study Results</relationshipLabel>
        <relationshipName>Plan_Of_Study_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Programme__c</fullName>
        <label>Special Programmes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reflection__c</fullName>
        <label>Thoughts &amp; Reflections for the year</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Recommended Tasks</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>isDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Plan Of Study Result</label>
    <nameField>
        <displayFormat>POSR-{0000000000}</displayFormat>
        <label>POS Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan Of Study Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Residential_College__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Residential College History</relationshipLabel>
        <relationshipName>Residential_Colleges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_From__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_To__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Residential_College_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residential College Name</label>
        <referenceTo>Residential_College_Master__c</referenceTo>
        <relationshipLabel>Residential Colleges</relationshipLabel>
        <relationshipName>Residential_Colleges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suite_No__c</fullName>
        <label>Suite No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Residential College</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Residential College ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residential Colleges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Residential_College_Master__c.object
<CustomObject>
    <label>Residential College Master</label>
    <nameField>
        <label>Residential College Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residential College Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Vice_Rector_Note_Module__c.object
<CustomObject>
    <label>Vice Rector Note Module</label>
    <nameField>
        <label>Module Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vice Rector Note Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/PlanOfStudyController.cls
public class PlanOfStudyController extends CommunityControllerBase{

    public Contact contact {set; get;}
    public Plan_Of_Study__c pos {set; get;}
    public List<Plan_Of_Study_Detail__c> posd {set; get;}
    //public List<Plan_Of_Study_Result__c> posr {set; get;}
    public Plan_Of_Study_Result__c posResult {set; get;}
    public List<Residential_College__c> residentialColleges;
    public String residentialCollegeName {set; get;}
    //public String today {set; get;}
    public List<Vice_Rector_Note_Module__c> modules {set; get;}
    public String posdIndexString {set; get;}
    public String posrIndexString {set; get;}
    
    
    private Map<String, String> params;
    private List<Plan_Of_Study_Detail__c> posdDelete {set; get;}
    //private List<Plan_Of_Study_Result__c> posrDelete {set; get;}
    
    public PlanOfStudyController(){
        params = this.getParameters();
        
        contact = [select Id,Name,Student_Identity__c,Email,Matric_Year__c,NRIC__c,Current_Year__c,Length_of_Course__c,Major__c,NUSNET_ID__c from Contact where Id =: ContactID];
        residentialColleges = [select Id,Name,Date_To__c,Date_From__c,Suite_No__c,Residential_College_Master__r.Name from Residential_College__c where Contact__c =: contact.Id and Date_To__c = null limit 1];
        
        if(residentialColleges.size() > 0){
            residentialCollegeName = residentialColleges.get(0).Residential_College_Master__r.Name;
        }else{
            residentialCollegeName = '';
        }
        
        posdDelete = new List<Plan_Of_Study_Detail__c>();
        //posrDelete = new List<Plan_Of_Study_Result__c>();
        
        if(params.get('status') == 'new'){
            //today = Datetime.now().format('dd MMMM yyyy');
            
            pos = new Plan_Of_Study__c();
            pos.Date__c = System.today();
            pos.Contact__c = contact.Id;
            pos.Year_Of_Study__c = contact.Current_Year__c;
            
            checkPOSData(contact.Id, contact.Current_Year__c);
        }else{
            pos = [select Id,Name,Contact__c,Date__c,Year_Of_Study__c,Faculty_Advisor__c,Head_of_Studies__c,Capstone_Advisor__c from Plan_Of_Study__c where Id =: params.get('pid')];
            posd = [select Id,Name,Semester__c,Module_Name__c,MC__c,Major_Request__c,Extra_curricular__c,Plan_Of_Study__c From Plan_Of_Study_Detail__c where Plan_Of_Study__c =: pos.Id];
            List<Plan_Of_Study_Result__c> posr = [select Id,Name,MC__c,CAP__c,Task__c,Programme__c,Career_Planning__c,Reflection__c,Plan_Of_Study__c From Plan_Of_Study_Result__c where Plan_Of_Study__c =: pos.Id];
            posResult = posr.get(0);
            
            Datetime dt = datetime.newInstance(pos.Date__c.Year(), pos.Date__c.Month(), pos.Date__c.Day());
            //today = dt.format('dd MMMM yyyy');
        }
    }
    
    private void checkPOSData(String contactId, String yearOfStudy){
        List<Plan_Of_Study__c> checkPOS = [select Id,Name,Contact__c,Date__c,Year_Of_Study__c,Faculty_Advisor__c,Head_of_Studies__c,Capstone_Advisor__c from Plan_Of_Study__c where Contact__c =: contactId and Year_Of_Study__c =: yearOfStudy];
        
        if(checkPOS.size() > 0){
            pos = checkPOS.get(0);
            
            posd = [select Id,Name,Semester__c,Module_Name__c,MC__c,Major_Request__c,Extra_curricular__c,Plan_Of_Study__c From Plan_Of_Study_Detail__c where Plan_Of_Study__c =: pos.Id and isDeleted__c = false];
            List<Plan_Of_Study_Result__c> posr = [select Id,Name,MC__c,CAP__c,Task__c,Programme__c,Career_Planning__c,Reflection__c,Plan_Of_Study__c From Plan_Of_Study_Result__c where Plan_Of_Study__c =: pos.Id and isDeleted__c = false];
            posResult = posr.get(0);
        }else{
            //today = Datetime.now().format('dd MMMM yyyy');
            
            pos = new Plan_Of_Study__c();
            pos.Date__c = System.today();
            pos.Contact__c = contact.Id;
            pos.Year_Of_Study__c = yearOfStudy;
            
            posd = new List<Plan_Of_Study_Detail__c>();
            posd.add(new Plan_Of_Study_Detail__c());
            
            //posr = new List<Plan_Of_Study_Result__c>();
            //posr.add(new Plan_Of_Study_Result__c());
            
            posResult = new Plan_Of_Study_Result__c();
        }
    }
    
    public void yearOfStudyOnChange(){
        checkPOSData(contact.Id, pos.Year_Of_Study__c);
    }
    
    public void posdAddRow(){
        posd.add(new Plan_Of_Study_Detail__c());
    }
    
    public void posdDeleteRow(){
        Integer index = Integer.valueOf(posdIndexString) - 1;
        
        Plan_Of_Study_Detail__c data = posd.get(index);
        posd.remove(index);
        
        if(String.isNotEmpty(data.Plan_Of_Study__c)){
            data.isDeleted__c = true;
            posdDelete.add(data);
        }
    }
    
    /*
    public void posrAddRow(){
        posr.add(new Plan_Of_Study_Result__c());
    }
    
    public void posrDeleteRow(){
        Integer index = Integer.valueOf(posrIndexString) - 1;
        
        Plan_Of_Study_Result__c data = posr.get(index);
        posr.remove(index);
        
        if(String.isNotEmpty(data.Plan_Of_Study__c)){
            data.isDeleted__c = true;
            posrDelete.add(data);
        }
    }
    */

    public PageReference save(){
        List<Plan_Of_Study_Detail__c> posdInsert = new List<Plan_Of_Study_Detail__c>();
        //List<Plan_Of_Study_result__c> posrInsert = new List<Plan_Of_Study_result__c>();
        
        List<Plan_Of_Study_Detail__c> posdUpdate = new List<Plan_Of_Study_Detail__c>();
        //List<Plan_Of_Study_result__c> posrUpdate = new List<Plan_Of_Study_result__c>();
        
        if(params.get('status') == 'new'){
            if(String.isNotEmpty(pos.Id)){
                update pos;    
            }else{
                insert pos;
            }
            
            for(Plan_Of_Study_Detail__c data : posd){
                if(String.isNotEmpty(data.Module_Name__c)){
                    if(String.isNotEmpty(data.Id)){
                        posdUpdate.add(data);   
                    }else{
                        data.Plan_Of_Study__c = pos.Id;
                        posdInsert.add(data);    
                    }
                }
            }
            
            /*
            for(Plan_Of_Study_Result__c data : posr){
                if(String.isNotEmpty(data.MC__c)){
                    if(String.isNotEmpty(data.Id)){
                        posrUpdate.add(data);   
                    }else{
                        data.Plan_Of_Study__c = pos.Id;
                        posrInsert.add(data);    
                    }
                }
            }
			*/
            
            if(String.isNotEmpty(posResult.MC__c)){
                if(String.isNotEmpty(posResult.Id)){
                    update posResult;
                }else{
                    posResult.Plan_Of_Study__c = pos.Id;
                    insert posResult;
                }
           	}            

            insert posdInsert;
            //insert posrInsert;
            
            update posdUpdate;
            //update posrUpdate;
        }else{
            update pos;
            
            for(Plan_Of_Study_Detail__c data : posd){
                if(String.isNotEmpty(data.Plan_Of_Study__c)){
                    posdUpdate.add(data);
                }else{
                    if(String.isNotEmpty(data.Module_Name__c)){
                        data.Plan_Of_Study__c = pos.Id;
                        posdInsert.add(data);
                    }
                }
            }
            
            /*
            for(Plan_Of_Study_Result__c data : posr){
                if(String.isNotEmpty(data.Plan_Of_Study__c)){
                    posrUpdate.add(data);
                }else{
                    if(String.isNotEmpty(data.MC__c)){
                        data.Plan_Of_Study__c = pos.Id;
                        posrInsert.add(data);
                    }    
                }
            }
            */
            
            if(String.isNotEmpty(posResult.Plan_Of_Study__c)){
                update posResult;
            }else{
                if(String.isNotEmpty(posResult.MC__c)){
                    posResult.Plan_Of_Study__c = pos.Id;
                    insert posResult;
               	}
            }
            
            insert posdInsert;
            //insert posrInsert;
            
            update posdUpdate;
            //update posrUpdate;
        }
        
        if(posdDelete.size() > 0){
            update posdDelete;
        }
        
        /*
        if(posrDelete.size() > 0){
            update posrDelete;
        }
        */
        
        return cancel();
    }
    
    public PageReference cancel(){
        return redirectToCaseView();
    }
}