unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Year__c</fullName>
        <label>Current Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_of_Course__c</fullName>
        <label>Length of Course</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Current Major</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Arts and Humanities</fullName>
                </value>
                <value>
                    <fullName>Economics</fullName>
                </value>
                <value>
                    <fullName>Environmental Studies</fullName>
                </value>
                <value>
                    <fullName>Global Affairs</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Literature</fullName>
                </value>
                <value>
                    <fullName>Mathematical and Computational Sciences</fullName>
                </value>
                <value>
                    <fullName>Philosophy</fullName>
                </value>
                <value>
                    <fullName>Physical Sciences</fullName>
                </value>
                <value>
                    <fullName>Politics, Philosophy and Economics</fullName>
                </value>
                <value>
                    <fullName>Psychology</fullName>
                </value>
                <value>
                    <fullName>Urban Studies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Matric_Year__c</fullName>
        <label>Matric Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NRIC__c</fullName>
        <label>NRIC/FIN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NUSNET_ID__c</fullName>
        <externalId>true</externalId>
        <label>NUSNET ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Semester 1</fullName>
                </value>
                <value>
                    <fullName>Semester 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student_Identity__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Student ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Faculty</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Head of Study</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Progress_Report__c.object
<CustomObject>
    <fields>
        <fullName>Academic_Advising__c</fullName>
        <label>Academic Advising</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Capstone_Advisor__c</fullName>
        <label>Capstone Advisor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Faculty_Advisor__c</fullName>
        <label>Faculty Advisor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Head_of_Study__c</fullName>
        <label>Head of Studies for Major</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Semester 2</fullName>
                </value>
                <value>
                    <fullName>Semester 1</fullName>
                    <isActive>false</isActive>
                    <label>Semester 1</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Academic Progress Reports</relationshipLabel>
        <relationshipName>Progress_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_of_Study__c</fullName>
        <label>Year of Study</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshmen</fullName>
                </value>
                <value>
                    <fullName>Sophomore</fullName>
                </value>
                <value>
                    <fullName>Junior</fullName>
                </value>
                <value>
                    <fullName>Senior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Progress Report</label>
    <nameField>
        <displayFormat>APR-{0000000000}</displayFormat>
        <label>Progress Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dean of Student</fullName>
                </value>
                <value>
                    <fullName>Faculty Advisor</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Divisional Director</fullName>
                </value>
                <value>
                    <fullName>Head of Study</fullName>
                </value>
                <value>
                    <fullName>Vice Rector</fullName>
                </value>
                <value>
                    <fullName>RC Exec</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/ProgressReportController.cls
public class ProgressReportController extends CommunityControllerBase{

    public Contact contact {set; get;}
    public Progress_Report__c progressReport {set; get;}
    public List<SelectOption> supervisorList {set; get;}
//    public String department {set; get;}
//    public String subDepartment {set; get;}
//    public String typeOfEnquiry {set; get;}
    
    private Map<String, String> params;
    
    public ProgressReportController(){
        params = this.getParameters();
        
        contact = [select Id,Name,Student_Identity__c,Email,Matric_Year__c,NRIC__c,Current_Year__c,Length_of_Course__c,Major__c,Semester__c,NUSNET_ID__c from Contact where Id =: ContactID];
        supervisorList = new List<SelectOption>();
        
        List<User> supervisorUsers = [select Name from User where Type__c includes('Supervisor')];
        for(User supervisorUser : supervisorUsers){
            supervisorList.add(new SelectOption(supervisorUser.Name, supervisorUser.Name));
        }

        if(params.get('status') == 'new'){
            progressReport = new Progress_Report__c();
            progressReport.Student__c = contact.Id;
            progressReport.Date__c = System.today();
            progressReport.Department__c = params.get('department');
            progressReport.Sub_Department__c = params.get('subdepartment');
            progressReport.Year_of_Study__c = contact.Current_Year__c;
            progressReport.Semester__c = contact.Semester__c;
            
//            checkProgressReportData(contact.Id, contact.Current_Year__c, contact.Semester__c);
        }else{
            progressReport = [select Id,Student__c,Academic_Advising__c,Semester__c,Year_of_Study__c,Head_of_Study__c,Capstone_Advisor__c,Faculty_Advisor__c from Progress_Report__c where Id =: params.get('pid')];
        }
    }
    
    private void checkProgressReportData(String contactId, String yearOfStudy, String semester){
        List<Progress_Report__c> pr = [select Id,Student__c,Academic_Advising__c,Semester__c,Year_of_Study__c,Head_of_Study__c,Capstone_Advisor__c,Faculty_Advisor__c from Progress_Report__c where Student__c =: contactId and Year_Of_Study__c =: yearOfStudy and Semester__c =: semester];
        
        if(pr.size() > 0){
            progressReport = pr.get(0);
        }else{
            progressReport = new Progress_Report__c();
            progressReport.Student__c = contact.Id;
            progressReport.Date__c = System.today();
            progressReport.Department__c = params.get('department');
            progressReport.Sub_Department__c = params.get('subdepartment');
            progressReport.Year_of_Study__c = yearOfStudy;
            progressReport.Semester__c = semester;
        }
    }
    
    public void yearOfStudyOnChange(){
//        checkProgressReportData(contact.Id, progressReport.Year_of_Study__c, progressReport.Semester__c);
    }
    
    public PageReference save(){
        if(String.isEmpty(progressReport.Year_of_Study__c)){
            this.showErrorMessage('Year of Study cannot be empty!');
            return null;
        }
        
        /*
        if(String.isEmpty(progressReport.Academic_Advising__c)){
            this.showErrorMessage('Academic Advising cannot be empty!');
            return null;
        }
		*/
        
        if(String.isEmpty(progressReport.Faculty_Advisor__c)){
            this.showErrorMessage('Faculty Advisor cannot be empty!');
            return null;
        }
        
        if(params.get('status') == 'new'){
            if(String.isNotEmpty(progressReport.Id)){
                update progressReport;    
            }else{
                insert progressReport;
            }
            
        }else{
            update progressReport;
        }
        
        return cancel();
    }
    
    public PageReference cancel(){
        return redirectToCaseView();
    }
}